import {FlowLevel} from './types';

export const LEVELS: FlowLevel[] = [

  {
    id: 1, title: 'First Flow', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,0], to:[2,1]},
      {key:'B', from:[1,1], to:[2,3]},
      {key:'G', from:[3,3], to:[2,0]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','B','B','B','G'],
      ['G','R','R','B','G'],
      ['R','R','R','G','G'],
      ['R','R','R','G','G'],
    ],
  },

  {
    id: 2, title: 'Two Lines', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,4], to:[1,0]},
      {key:'B', from:[0,0], to:[0,3]},
      {key:'G', from:[1,3], to:[0,4]},
    ],
    solution: [
      ['B','B','B','B','G'],
      ['R','R','R','G','G'],
      ['R','R','R','G','G'],
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 3, title: 'Corner Turn', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,4], to:[3,3]},
      {key:'B', from:[3,4], to:[4,4]},
      {key:'G', from:[4,3], to:[4,0]},
    ],
    solution: [
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
      ['R','R','R','R','B'],
      ['G','G','G','G','B'],
    ],
  },

  {
    id: 4, title: 'Crossroads', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,0], to:[3,3]},
      {key:'B', from:[2,3], to:[3,1]},
      {key:'G', from:[2,1], to:[0,4]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','G','B','B','B'],
      ['R','G','B','B','B'],
      ['R','B','B','R','R'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 5, title: 'Little Loop', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[1,3], to:[3,2]},
      {key:'B', from:[3,3], to:[1,0]},
      {key:'G', from:[0,0], to:[1,2]},
      {key:'Y', from:[1,1], to:[3,1]},
    ],
    solution: [
      ['G','G','G','R','R'],
      ['B','Y','G','R','R'],
      ['B','Y','R','R','R'],
      ['B','Y','R','B','B'],
      ['B','B','B','B','B'],
    ],
  },

  {
    id: 6, title: 'Side Step', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[0,2], to:[4,4]},
      {key:'B', from:[4,3], to:[3,2]},
      {key:'G', from:[4,2], to:[1,2]},
      {key:'Y', from:[1,3], to:[2,2]},
    ],
    solution: [
      ['G','G','R','R','R'],
      ['G','G','G','Y','R'],
      ['G','G','Y','Y','R'],
      ['G','G','B','B','R'],
      ['G','G','G','B','R'],
    ],
  },

  {
    id: 7, title: 'Twin Paths', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[0,0], to:[4,2]},
      {key:'B', from:[4,3], to:[2,2]},
      {key:'G', from:[2,3], to:[0,3]},
      {key:'Y', from:[1,3], to:[3,1]},
    ],
    solution: [
      ['R','Y','Y','G','G'],
      ['R','Y','Y','Y','G'],
      ['R','Y','B','G','G'],
      ['R','Y','B','B','B'],
      ['R','R','R','B','B'],
    ],
  },

  {
    id: 8, title: 'Zig Zag', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,4], to:[1,1]},
      {key:'B', from:[1,0], to:[2,3]},
      {key:'G', from:[1,3], to:[3,4]},
      {key:'Y', from:[3,3], to:[3,1]},
    ],
    solution: [
      ['B','B','B','G','G'],
      ['B','R','B','G','G'],
      ['R','R','B','B','G'],
      ['R','Y','Y','Y','G'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 9, title: 'Box In', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[3,3], to:[0,4]},
      {key:'B', from:[0,3], to:[0,1]},
      {key:'G', from:[0,0], to:[3,0]},
      {key:'Y', from:[4,0], to:[4,2]},
      {key:'O', from:[4,3], to:[2,2]},
    ],
    solution: [
      ['G','B','B','B','R'],
      ['G','R','R','R','R'],
      ['G','R','O','O','O'],
      ['G','R','R','R','O'],
      ['Y','Y','Y','O','O'],
    ],
  },

  {
    id: 10, title: 'Five Ways', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[3,1], to:[2,0]},
      {key:'B', from:[3,0], to:[2,3]},
      {key:'G', from:[1,3], to:[1,0]},
      {key:'Y', from:[0,0], to:[0,3]},
      {key:'O', from:[0,4], to:[3,3]},
    ],
    solution: [
      ['Y','Y','Y','Y','O'],
      ['G','G','G','G','O'],
      ['R','R','B','B','O'],
      ['B','R','B','O','O'],
      ['B','B','B','O','O'],
    ],
  },

  {
    id: 11, title: 'River Bend', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,5], to:[3,3]},
      {key:'B', from:[3,2], to:[4,0]},
      {key:'G', from:[3,0], to:[1,4]},
      {key:'Y', from:[1,3], to:[2,2]},
    ],
    solution: [
      ['G','G','G','G','G','G'],
      ['G','Y','Y','Y','G','G'],
      ['G','Y','Y','R','R','R'],
      ['G','B','B','R','R','R'],
      ['B','B','R','R','R','R'],
      ['B','B','R','R','R','R'],
    ],
  },

  {
    id: 12, title: 'Tangle', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[0,5], to:[1,4]},
      {key:'B', from:[0,4], to:[1,0]},
      {key:'G', from:[2,0], to:[5,2]},
      {key:'Y', from:[5,3], to:[1,3]},
    ],
    solution: [
      ['B','B','B','B','B','R'],
      ['B','B','B','Y','R','R'],
      ['G','B','B','Y','R','R'],
      ['G','G','G','Y','R','R'],
      ['G','G','G','Y','R','R'],
      ['G','G','G','Y','R','R'],
    ],
  },

  {
    id: 13, title: 'Knot', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[2,3], to:[5,4]},
      {key:'B', from:[5,3], to:[3,1]},
      {key:'G', from:[2,1], to:[3,4]},
      {key:'Y', from:[3,5], to:[0,4]},
    ],
    solution: [
      ['G','G','G','G','Y','Y'],
      ['G','G','G','G','G','Y'],
      ['G','G','R','R','G','Y'],
      ['B','B','R','R','G','Y'],
      ['B','B','B','R','R','R'],
      ['B','B','B','B','R','R'],
    ],
  },

  {
    id: 14, title: 'Switchback', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[2,0], to:[4,1]},
      {key:'B', from:[3,1], to:[4,3]},
      {key:'G', from:[4,2], to:[3,4]},
      {key:'Y', from:[3,5], to:[1,0]},
    ],
    solution: [
      ['Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','Y'],
      ['R','Y','Y','Y','Y','Y'],
      ['R','B','B','B','G','Y'],
      ['R','R','G','B','G','G'],
      ['R','R','G','G','G','G'],
    ],
  },

  {
    id: 15, title: 'Detour', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[2,3], to:[3,1]},
      {key:'B', from:[2,1], to:[4,4]},
      {key:'G', from:[3,4], to:[0,2]},
      {key:'Y', from:[0,1], to:[1,0]},
      {key:'O', from:[1,1], to:[1,3]},
    ],
    solution: [
      ['Y','Y','G','G','G','G'],
      ['Y','O','O','O','G','G'],
      ['B','B','R','R','G','G'],
      ['B','R','R','R','G','G'],
      ['B','R','R','R','B','B'],
      ['B','B','B','B','B','B'],
    ],
  },

  {
    id: 16, title: 'Spiral', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,3], to:[4,5]},
      {key:'B', from:[3,5], to:[2,3]},
      {key:'G', from:[1,3], to:[0,2]},
      {key:'Y', from:[1,2], to:[5,0]},
      {key:'O', from:[4,0], to:[2,1]},
    ],
    solution: [
      ['O','O','G','G','B','B'],
      ['O','O','Y','G','B','B'],
      ['O','O','Y','B','B','B'],
      ['O','O','Y','R','R','B'],
      ['O','O','Y','R','R','R'],
      ['Y','Y','Y','R','R','R'],
    ],
  },

  {
    id: 17, title: 'Weave', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,1], to:[2,2]},
      {key:'B', from:[2,3], to:[3,3]},
      {key:'G', from:[3,4], to:[5,4]},
      {key:'Y', from:[4,4], to:[4,0]},
      {key:'O', from:[3,0], to:[1,4]},
    ],
    solution: [
      ['O','O','O','O','O','O'],
      ['O','O','O','O','O','O'],
      ['O','O','R','B','O','O'],
      ['O','R','R','B','G','G'],
      ['Y','Y','Y','Y','Y','G'],
      ['Y','Y','Y','Y','G','G'],
    ],
  },

  {
    id: 18, title: 'Lattice', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,1], to:[3,2]},
      {key:'B', from:[4,2], to:[5,3]},
      {key:'G', from:[4,3], to:[5,5]},
      {key:'Y', from:[4,5], to:[2,4]},
      {key:'O', from:[3,4], to:[1,1]},
    ],
    solution: [
      ['O','O','O','O','Y','Y'],
      ['O','O','O','O','Y','Y'],
      ['R','R','O','O','Y','Y'],
      ['R','R','R','O','O','Y'],
      ['R','R','B','G','G','Y'],
      ['R','R','B','B','G','G'],
    ],
  },

  {
    id: 19, title: 'Coil', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[1,4], to:[0,5]},
      {key:'B', from:[0,4], to:[0,3]},
      {key:'G', from:[1,3], to:[3,4]},
      {key:'Y', from:[2,4], to:[4,5]},
      {key:'O', from:[5,5], to:[4,1]},
      {key:'P', from:[4,2], to:[2,0]},
    ],
    solution: [
      ['P','P','P','B','B','R'],
      ['P','P','P','G','R','R'],
      ['P','P','P','G','Y','Y'],
      ['O','O','P','G','G','Y'],
      ['O','O','P','G','G','Y'],
      ['O','O','O','O','O','O'],
    ],
  },

  {
    id: 20, title: 'Maze Start', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,3], to:[2,2]},
      {key:'B', from:[3,2], to:[1,1]},
      {key:'G', from:[1,2], to:[4,4]},
      {key:'Y', from:[4,3], to:[0,3]},
      {key:'O', from:[0,2], to:[5,1]},
      {key:'P', from:[5,2], to:[4,1]},
    ],
    solution: [
      ['O','O','O','Y','Y','Y'],
      ['O','B','G','G','G','Y'],
      ['O','B','R','R','G','Y'],
      ['O','B','B','R','G','Y'],
      ['O','P','P','Y','G','Y'],
      ['O','O','P','Y','Y','Y'],
    ],
  },

  {
    id: 21, title: 'Crosswind', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[0,4], to:[3,1]},
      {key:'B', from:[3,0], to:[5,3]},
      {key:'G', from:[5,2], to:[4,3]},
      {key:'Y', from:[4,4], to:[6,6]},
      {key:'O', from:[5,6], to:[1,5]},
    ],
    solution: [
      ['R','R','R','R','R','O','O'],
      ['R','R','R','R','R','O','O'],
      ['R','R','R','R','O','O','O'],
      ['B','R','R','R','O','O','O'],
      ['B','B','G','G','Y','Y','O'],
      ['B','B','G','B','B','Y','O'],
      ['B','B','B','B','B','Y','Y'],
    ],
  },

  {
    id: 22, title: 'Braid', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[0,0], to:[0,5]},
      {key:'B', from:[0,6], to:[6,3]},
      {key:'G', from:[6,2], to:[5,0]},
      {key:'Y', from:[4,0], to:[2,1]},
      {key:'O', from:[3,1], to:[5,3]},
    ],
    solution: [
      ['R','R','R','R','R','R','B'],
      ['Y','Y','O','O','O','O','B'],
      ['Y','Y','O','O','O','O','B'],
      ['Y','O','O','O','O','B','B'],
      ['Y','O','O','O','O','B','B'],
      ['G','O','O','O','B','B','B'],
      ['G','G','G','B','B','B','B'],
    ],
  },

  {
    id: 23, title: 'Snarl', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[1,1], to:[4,1]},
      {key:'B', from:[5,1], to:[5,4]},
      {key:'G', from:[5,5], to:[0,4]},
      {key:'Y', from:[1,4], to:[2,5]},
      {key:'O', from:[2,4], to:[4,4]},
    ],
    solution: [
      ['G','G','G','G','G','Y','Y'],
      ['G','R','G','G','Y','Y','Y'],
      ['G','R','G','G','O','Y','Y'],
      ['G','R','R','R','O','G','G'],
      ['G','R','R','R','O','G','G'],
      ['G','B','B','B','B','G','G'],
      ['G','G','G','G','G','G','G'],
    ],
  },

  {
    id: 24, title: 'Labyrinth', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[6,0], to:[3,6]},
      {key:'B', from:[4,6], to:[3,5]},
      {key:'G', from:[3,4], to:[3,2]},
      {key:'Y', from:[3,1], to:[4,3]},
      {key:'O', from:[5,3], to:[4,4]},
    ],
    solution: [
      ['R','R','R','R','R','R','R'],
      ['R','R','R','R','R','R','R'],
      ['R','R','R','R','R','R','R'],
      ['R','Y','G','G','G','B','R'],
      ['R','Y','Y','Y','O','B','B'],
      ['R','R','R','O','O','B','B'],
      ['R','R','R','O','O','B','B'],
    ],
  },

  {
    id: 25, title: 'Long Haul', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[6,2], to:[6,6]},
      {key:'B', from:[5,6], to:[0,6]},
      {key:'G', from:[0,5], to:[0,0]},
      {key:'Y', from:[1,0], to:[3,0]},
      {key:'O', from:[3,1], to:[5,1]},
      {key:'P', from:[6,1], to:[4,4]},
    ],
    solution: [
      ['G','G','G','G','G','G','B'],
      ['Y','O','O','O','O','O','B'],
      ['Y','O','P','P','P','O','B'],
      ['Y','O','P','P','P','O','B'],
      ['P','P','P','P','P','O','B'],
      ['P','O','O','O','O','O','B'],
      ['P','P','R','R','R','R','R'],
    ],
  },

  {
    id: 26, title: 'Gridlock', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[2,0], to:[0,4]},
      {key:'B', from:[1,4], to:[0,6]},
      {key:'G', from:[1,6], to:[3,2]},
      {key:'Y', from:[3,3], to:[6,2]},
      {key:'O', from:[6,3], to:[5,5]},
      {key:'P', from:[5,4], to:[5,1]},
    ],
    solution: [
      ['R','R','R','R','R','B','B'],
      ['R','G','G','G','B','B','G'],
      ['R','G','G','G','G','G','G'],
      ['Y','Y','G','Y','O','O','O'],
      ['Y','Y','Y','Y','O','O','O'],
      ['Y','P','P','P','P','O','O'],
      ['Y','Y','Y','O','O','O','O'],
    ],
  },

  {
    id: 27, title: 'Tight Squeeze', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[4,2], to:[1,2]},
      {key:'B', from:[1,1], to:[0,3]},
      {key:'G', from:[1,3], to:[6,6]},
      {key:'Y', from:[6,5], to:[5,2]},
      {key:'O', from:[6,2], to:[5,1]},
      {key:'P', from:[4,1], to:[2,0]},
    ],
    solution: [
      ['B','B','B','B','G','G','G'],
      ['B','B','R','G','G','G','G'],
      ['P','R','R','G','G','G','G'],
      ['P','R','R','G','G','G','G'],
      ['P','P','R','G','G','G','G'],
      ['O','O','Y','Y','Y','Y','G'],
      ['O','O','O','Y','Y','Y','G'],
    ],
  },

  {
    id: 28, title: 'Overpass', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[4,4], to:[0,6]},
      {key:'B', from:[0,5], to:[0,3]},
      {key:'G', from:[1,3], to:[5,3]},
      {key:'Y', from:[5,4], to:[6,2]},
      {key:'O', from:[5,2], to:[3,0]},
      {key:'P', from:[2,0], to:[0,2]},
    ],
    solution: [
      ['P','P','P','B','B','B','R'],
      ['P','G','G','G','R','R','R'],
      ['P','G','G','G','R','R','R'],
      ['O','O','O','G','R','R','R'],
      ['O','O','O','G','R','R','R'],
      ['O','O','O','G','Y','R','R'],
      ['O','O','Y','Y','Y','R','R'],
    ],
  },

  {
    id: 29, title: 'Junction', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[5,5], to:[4,6]},
      {key:'B', from:[4,5], to:[6,2]},
      {key:'G', from:[5,2], to:[3,2]},
      {key:'Y', from:[3,3], to:[2,4]},
      {key:'O', from:[2,3], to:[0,1]},
      {key:'P', from:[0,0], to:[6,1]},
      {key:'T', from:[6,0], to:[2,0]},
    ],
    solution: [
      ['P','O','O','O','Y','Y','Y'],
      ['P','P','O','O','Y','Y','Y'],
      ['T','P','O','O','Y','Y','Y'],
      ['T','P','G','Y','Y','Y','Y'],
      ['T','P','G','B','B','B','R'],
      ['T','P','G','B','B','R','R'],
      ['T','P','B','B','B','R','R'],
    ],
  },

  {
    id: 30, title: 'Crossover', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[4,2], to:[2,4]},
      {key:'B', from:[2,3], to:[0,1]},
      {key:'G', from:[0,0], to:[3,0]},
      {key:'Y', from:[3,1], to:[5,0]},
      {key:'O', from:[6,0], to:[5,1]},
      {key:'P', from:[5,2], to:[6,5]},
      {key:'T', from:[6,6], to:[4,6]},
    ],
    solution: [
      ['G','B','B','B','B','B','B'],
      ['G','G','G','B','B','B','B'],
      ['G','G','G','B','R','T','T'],
      ['G','Y','R','R','R','T','T'],
      ['Y','Y','R','R','R','T','T'],
      ['Y','O','P','P','P','T','T'],
      ['O','O','P','P','P','P','T'],
    ],
  },

  {
    id: 31, title: 'Deep Dive', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[5,4], to:[4,3]},
      {key:'B', from:[5,3], to:[6,2]},
      {key:'G', from:[6,1], to:[3,3]},
      {key:'Y', from:[2,3], to:[1,2]},
      {key:'O', from:[1,3], to:[1,7]},
      {key:'P', from:[0,7], to:[2,0]},
    ],
    solution: [
      ['P','P','P','P','P','P','P','P'],
      ['P','P','Y','O','O','O','O','O'],
      ['P','P','Y','Y','G','G','G','G'],
      ['P','P','P','G','G','G','G','G'],
      ['P','P','P','R','R','G','G','G'],
      ['P','P','B','B','R','G','G','G'],
      ['G','G','B','G','G','G','G','G'],
      ['G','G','G','G','G','G','G','G'],
    ],
  },

  {
    id: 32, title: 'Web', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,4], to:[2,2]},
      {key:'B', from:[2,3], to:[6,4]},
      {key:'G', from:[6,5], to:[4,7]},
      {key:'Y', from:[5,7], to:[7,5]},
      {key:'O', from:[7,4], to:[3,0]},
      {key:'P', from:[2,0], to:[1,5]},
    ],
    solution: [
      ['P','P','P','P','P','P','P','P'],
      ['P','R','R','R','R','P','P','P'],
      ['P','R','R','B','B','P','P','P'],
      ['O','O','O','O','B','P','P','P'],
      ['O','O','O','O','B','G','G','G'],
      ['O','O','O','B','B','G','G','Y'],
      ['O','O','O','B','B','G','G','Y'],
      ['O','O','O','O','O','Y','Y','Y'],
    ],
  },

  {
    id: 33, title: 'Mesh', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[6,6], to:[7,4]},
      {key:'B', from:[7,5], to:[5,7]},
      {key:'G', from:[4,7], to:[2,4]},
      {key:'Y', from:[2,5], to:[1,1]},
      {key:'O', from:[0,1], to:[5,0]},
      {key:'P', from:[6,0], to:[5,2]},
    ],
    solution: [
      ['O','O','G','G','G','G','G','G'],
      ['O','Y','G','G','G','Y','Y','G'],
      ['O','Y','Y','Y','G','Y','Y','G'],
      ['O','Y','Y','Y','Y','Y','Y','G'],
      ['O','Y','Y','Y','Y','R','R','G'],
      ['O','P','P','Y','Y','R','R','B'],
      ['P','P','R','R','R','R','R','B'],
      ['P','P','R','R','R','B','B','B'],
    ],
  },

  {
    id: 34, title: 'Puzzle Box', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[5,1], to:[5,3]},
      {key:'B', from:[6,3], to:[4,3]},
      {key:'G', from:[3,3], to:[2,6]},
      {key:'Y', from:[3,6], to:[3,0]},
      {key:'O', from:[4,0], to:[7,2]},
      {key:'P', from:[7,3], to:[6,5]},
    ],
    solution: [
      ['Y','Y','Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','G','G','Y'],
      ['Y','Y','Y','G','G','G','Y','Y'],
      ['O','R','R','B','B','B','Y','Y'],
      ['O','R','R','R','B','B','Y','Y'],
      ['O','O','O','B','B','P','P','P'],
      ['O','O','O','P','P','P','P','P'],
    ],
  },

  {
    id: 35, title: 'Entangled', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[3,2], to:[4,6]},
      {key:'B', from:[4,7], to:[7,6]},
      {key:'G', from:[7,5], to:[7,3]},
      {key:'Y', from:[7,2], to:[3,0]},
      {key:'O', from:[2,0], to:[0,1]},
      {key:'P', from:[0,2], to:[1,4]},
      {key:'T', from:[1,3], to:[4,4]},
    ],
    solution: [
      ['O','O','P','P','P','T','T','T'],
      ['O','R','R','T','P','T','T','T'],
      ['O','R','R','T','T','T','T','T'],
      ['Y','R','R','T','T','T','T','T'],
      ['Y','R','R','T','T','R','R','B'],
      ['Y','Y','R','T','T','R','R','B'],
      ['Y','Y','R','R','R','R','R','B'],
      ['Y','Y','Y','G','G','G','B','B'],
    ],
  },

  {
    id: 36, title: 'Crisscross', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[7,5], to:[7,2]},
      {key:'B', from:[7,1], to:[2,0]},
      {key:'G', from:[1,0], to:[2,6]},
      {key:'Y', from:[2,7], to:[5,5]},
      {key:'O', from:[4,5], to:[1,4]},
      {key:'P', from:[2,4], to:[1,1]},
      {key:'T', from:[2,1], to:[5,2]},
    ],
    solution: [
      ['G','G','G','G','G','G','G','G'],
      ['G','P','P','P','O','O','G','G'],
      ['B','T','T','P','P','O','G','Y'],
      ['B','T','T','T','T','O','O','Y'],
      ['B','T','T','T','T','O','O','Y'],
      ['B','B','T','T','T','Y','Y','Y'],
      ['B','B','R','R','R','R','Y','Y'],
      ['B','B','R','R','R','R','Y','Y'],
    ],
  },

  {
    id: 37, title: 'Convolution', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,6], to:[7,3]},
      {key:'B', from:[7,2], to:[4,3]},
      {key:'G', from:[5,3], to:[3,2]},
      {key:'Y', from:[3,3], to:[2,1]},
      {key:'O', from:[3,1], to:[1,4]},
      {key:'P', from:[0,4], to:[1,7]},
      {key:'T', from:[1,6], to:[4,5]},
    ],
    solution: [
      ['O','O','O','O','P','P','P','P'],
      ['O','Y','Y','O','O','T','T','P'],
      ['O','Y','Y','Y','Y','T','R','R'],
      ['O','O','G','Y','Y','T','T','R'],
      ['B','B','G','B','B','T','T','R'],
      ['B','B','G','G','B','T','T','R'],
      ['B','B','B','B','B','R','R','R'],
      ['B','B','B','R','R','R','R','R'],
    ],
  },

  {
    id: 38, title: 'The Gauntlet', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,3], to:[1,1]},
      {key:'B', from:[0,1], to:[4,4]},
      {key:'G', from:[4,5], to:[6,4]},
      {key:'Y', from:[5,4], to:[7,7]},
      {key:'O', from:[6,7], to:[1,5]},
      {key:'P', from:[1,4], to:[1,2]},
      {key:'T', from:[0,2], to:[3,7]},
    ],
    solution: [
      ['B','B','T','T','T','T','T','T'],
      ['B','R','P','P','P','O','T','T'],
      ['B','R','R','R','R','O','T','T'],
      ['B','B','R','R','R','O','O','T'],
      ['B','B','B','B','B','G','O','O'],
      ['B','B','B','Y','Y','G','G','O'],
      ['Y','Y','Y','Y','G','G','G','O'],
      ['Y','Y','Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 39, title: 'Serpentine', difficulty: 'expert', gridSize: 8,
    dots: [
      {key:'R', from:[2,1], to:[3,2]},
      {key:'B', from:[3,3], to:[2,4]},
      {key:'G', from:[3,4], to:[2,0]},
      {key:'Y', from:[3,0], to:[6,2]},
      {key:'O', from:[5,2], to:[6,5]},
      {key:'P', from:[7,5], to:[1,7]},
      {key:'T', from:[0,7], to:[0,5]},
      {key:'K', from:[0,4], to:[0,2]},
    ],
    solution: [
      ['G','G','K','K','K','T','T','T'],
      ['G','G','G','G','G','G','P','P'],
      ['G','R','R','B','B','G','P','P'],
      ['Y','Y','R','B','G','G','G','P'],
      ['Y','Y','O','O','G','G','G','P'],
      ['Y','Y','O','O','G','G','P','P'],
      ['Y','Y','Y','O','O','O','P','P'],
      ['Y','Y','Y','O','O','P','P','P'],
    ],
  },

  {
    id: 40, title: 'Big Knot', difficulty: 'expert', gridSize: 8,
    dots: [
      {key:'R', from:[3,3], to:[6,2]},
      {key:'B', from:[6,3], to:[2,4]},
      {key:'G', from:[2,3], to:[1,0]},
      {key:'Y', from:[1,1], to:[2,0]},
      {key:'O', from:[3,0], to:[6,4]},
      {key:'P', from:[5,4], to:[6,7]},
      {key:'T', from:[5,7], to:[0,6]},
      {key:'K', from:[0,5], to:[2,5]},
    ],
    solution: [
      ['G','G','G','G','K','K','T','T'],
      ['G','Y','G','G','K','K','K','T'],
      ['Y','Y','G','G','B','K','K','T'],
      ['O','O','R','R','B','T','T','T'],
      ['O','O','R','B','B','T','T','T'],
      ['O','R','R','B','P','P','P','T'],
      ['O','R','R','B','O','P','P','P'],
      ['O','O','O','O','O','P','P','P'],
    ],
  },

  {
    id: 41, title: 'Floodgate', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[7,7], to:[1,2]},
      {key:'B', from:[1,3], to:[8,2]},
      {key:'G', from:[8,3], to:[8,5]},
      {key:'Y', from:[7,5], to:[5,3]},
      {key:'O', from:[5,2], to:[3,3]},
      {key:'P', from:[3,4], to:[4,7]},
      {key:'T', from:[5,7], to:[3,5]},
    ],
    solution: [
      ['R','R','R','R','R','R','R','R','R'],
      ['R','R','R','B','R','R','R','R','R'],
      ['B','B','B','B','P','P','P','P','R'],
      ['B','O','O','O','P','T','T','P','R'],
      ['B','O','O','O','T','T','T','P','R'],
      ['B','O','O','Y','T','T','T','T','R'],
      ['B','B','B','Y','T','T','T','T','R'],
      ['B','B','B','Y','Y','Y','R','R','R'],
      ['B','B','B','G','G','G','R','R','R'],
    ],
  },

  {
    id: 42, title: 'Conduit', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[4,6], to:[8,6]},
      {key:'B', from:[8,5], to:[8,3]},
      {key:'G', from:[8,2], to:[3,2]},
      {key:'Y', from:[2,2], to:[0,1]},
      {key:'O', from:[1,1], to:[1,5]},
      {key:'P', from:[1,4], to:[4,8]},
      {key:'T', from:[5,8], to:[3,3]},
    ],
    solution: [
      ['Y','Y','O','O','P','P','P','P','P'],
      ['Y','O','O','O','P','O','P','P','P'],
      ['Y','Y','Y','O','O','O','T','T','P'],
      ['Y','Y','G','T','T','T','T','T','P'],
      ['Y','Y','G','G','T','T','R','T','P'],
      ['G','G','G','G','R','R','R','T','T'],
      ['G','G','G','R','R','R','R','R','R'],
      ['G','G','G','R','R','R','R','R','R'],
      ['G','G','G','B','B','B','R','R','R'],
    ],
  },

  {
    id: 43, title: 'Plexus', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[3,1], to:[0,2]},
      {key:'B', from:[0,3], to:[1,6]},
      {key:'G', from:[1,5], to:[4,0]},
      {key:'Y', from:[5,0], to:[8,0]},
      {key:'O', from:[8,1], to:[6,1]},
      {key:'P', from:[6,2], to:[3,8]},
      {key:'T', from:[4,8], to:[3,7]},
    ],
    solution: [
      ['R','R','R','B','B','B','B','B','B'],
      ['R','G','G','G','G','G','B','B','B'],
      ['R','G','G','G','G','P','P','P','P'],
      ['R','R','G','G','G','P','P','T','P'],
      ['G','G','G','G','G','P','P','T','T'],
      ['Y','G','G','P','P','P','T','T','T'],
      ['Y','O','P','P','P','P','T','T','T'],
      ['Y','O','P','P','P','P','P','T','T'],
      ['Y','O','P','P','P','P','P','T','T'],
    ],
  },

  {
    id: 44, title: 'Quagmire', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,7], to:[0,5]},
      {key:'B', from:[0,4], to:[0,2]},
      {key:'G', from:[0,1], to:[2,0]},
      {key:'Y', from:[3,0], to:[6,5]},
      {key:'O', from:[6,6], to:[1,6]},
      {key:'P', from:[1,5], to:[6,4]},
      {key:'T', from:[7,4], to:[6,2]},
    ],
    solution: [
      ['G','G','B','B','B','R','R','R','R'],
      ['G','G','B','B','P','P','O','R','R'],
      ['G','G','Y','Y','P','P','O','O','O'],
      ['Y','Y','Y','Y','P','P','O','O','O'],
      ['Y','Y','Y','Y','P','P','O','O','O'],
      ['Y','Y','Y','P','P','P','O','O','O'],
      ['Y','Y','T','P','P','Y','O','Y','Y'],
      ['Y','Y','T','T','T','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 45, title: 'The Weaver', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[3,5], to:[3,7]},
      {key:'B', from:[4,7], to:[5,8]},
      {key:'G', from:[4,8], to:[0,8]},
      {key:'Y', from:[0,7], to:[1,4]},
      {key:'O', from:[0,4], to:[7,0]},
      {key:'P', from:[8,0], to:[8,6]},
      {key:'T', from:[8,7], to:[4,3]},
      {key:'K', from:[5,3], to:[7,7]},
    ],
    solution: [
      ['O','O','O','O','O','Y','Y','Y','G'],
      ['O','Y','Y','Y','Y','Y','Y','Y','G'],
      ['O','Y','Y','Y','Y','Y','Y','Y','G'],
      ['O','O','O','Y','Y','R','R','R','G'],
      ['O','O','O','T','T','T','T','B','G'],
      ['O','O','O','K','T','T','T','B','B'],
      ['O','O','O','K','T','T','T','T','T'],
      ['O','O','O','K','K','K','K','K','T'],
      ['P','P','P','P','P','P','P','T','T'],
    ],
  },

  {
    id: 46, title: 'Gordian', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[0,2], to:[0,0]},
      {key:'B', from:[1,0], to:[6,0]},
      {key:'G', from:[7,0], to:[1,5]},
      {key:'Y', from:[1,4], to:[1,8]},
      {key:'O', from:[2,8], to:[6,5]},
      {key:'P', from:[5,5], to:[4,7]},
      {key:'T', from:[3,7], to:[4,5]},
      {key:'K', from:[4,4], to:[7,5]},
    ],
    solution: [
      ['R','R','R','Y','Y','Y','Y','Y','Y'],
      ['B','R','R','Y','Y','G','T','T','Y'],
      ['B','R','R','G','G','G','T','T','O'],
      ['B','G','G','G','G','G','T','T','O'],
      ['B','G','G','G','K','T','T','P','O'],
      ['B','G','G','G','K','P','P','P','O'],
      ['B','G','G','G','K','O','O','O','O'],
      ['G','G','G','K','K','K','K','O','O'],
      ['G','G','G','K','K','K','K','O','O'],
    ],
  },

  {
    id: 47, title: 'Pipework', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[0,6], to:[0,8]},
      {key:'B', from:[1,8], to:[3,6]},
      {key:'G', from:[3,5], to:[0,5]},
      {key:'Y', from:[0,4], to:[1,1]},
      {key:'O', from:[0,1], to:[6,0]},
      {key:'P', from:[7,0], to:[4,3]},
      {key:'T', from:[3,3], to:[7,8]},
      {key:'K', from:[8,8], to:[8,4]},
    ],
    solution: [
      ['O','O','Y','Y','Y','G','R','R','R'],
      ['O','Y','Y','Y','Y','G','R','R','B'],
      ['O','P','P','T','T','G','B','B','B'],
      ['O','P','P','T','T','G','B','B','B'],
      ['O','P','P','P','T','T','T','T','T'],
      ['O','P','P','P','T','T','T','T','T'],
      ['O','P','P','P','T','T','K','K','T'],
      ['P','P','P','P','T','T','K','K','T'],
      ['P','P','P','P','K','K','K','K','K'],
    ],
  },

  {
    id: 48, title: 'Grand Maze', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,3], to:[0,2]},
      {key:'B', from:[0,3], to:[0,5]},
      {key:'G', from:[0,6], to:[0,8]},
      {key:'Y', from:[1,8], to:[5,7]},
      {key:'O', from:[5,8], to:[7,8]},
      {key:'P', from:[8,8], to:[3,0]},
      {key:'T', from:[2,0], to:[3,1]},
      {key:'K', from:[3,2], to:[1,7]},
    ],
    solution: [
      ['T','T','R','B','B','B','G','G','G'],
      ['T','T','R','R','K','K','K','K','Y'],
      ['T','T','R','R','K','K','K','K','Y'],
      ['P','T','K','K','K','K','K','K','Y'],
      ['P','K','K','K','K','K','K','Y','Y'],
      ['P','K','K','K','K','K','K','Y','O'],
      ['P','P','K','K','K','P','P','O','O'],
      ['P','P','K','K','K','P','P','O','O'],
      ['P','P','P','P','P','P','P','P','P'],
    ],
  },

  {
    id: 49, title: 'Master Flow', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[2,8], to:[0,7]},
      {key:'B', from:[0,6], to:[1,2]},
      {key:'G', from:[2,2], to:[5,2]},
      {key:'Y', from:[5,1], to:[6,0]},
      {key:'O', from:[7,0], to:[7,2]},
      {key:'P', from:[7,1], to:[6,3]},
      {key:'T', from:[5,3], to:[5,6]},
      {key:'K', from:[6,6], to:[7,5]},
      {key:'N', from:[7,6], to:[8,8]},
    ],
    solution: [
      ['B','B','B','B','B','B','B','R','R'],
      ['B','B','B','B','B','B','R','R','R'],
      ['G','G','G','B','B','B','R','R','R'],
      ['G','G','G','B','B','T','T','R','R'],
      ['Y','Y','G','B','B','T','T','R','R'],
      ['Y','Y','G','T','T','T','T','N','N'],
      ['Y','P','P','P','K','K','K','N','N'],
      ['O','P','O','O','K','K','N','N','N'],
      ['O','O','O','O','K','K','N','N','N'],
    ],
  },

  {
    id: 50, title: 'Flow Master', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,2], to:[6,4]},
      {key:'B', from:[7,4], to:[7,1]},
      {key:'G', from:[6,1], to:[5,2]},
      {key:'Y', from:[4,2], to:[4,7]},
      {key:'O', from:[5,7], to:[6,5]},
      {key:'P', from:[7,5], to:[0,6]},
      {key:'T', from:[0,5], to:[1,1]},
      {key:'K', from:[0,1], to:[3,4]},
      {key:'N', from:[2,4], to:[1,7]},
    ],
    solution: [
      ['K','K','T','T','T','T','P','P','P'],
      ['K','T','T','T','T','T','N','N','P'],
      ['K','T','T','T','N','N','N','P','P'],
      ['K','K','K','K','K','N','N','P','P'],
      ['K','K','Y','Y','Y','Y','Y','Y','P'],
      ['G','G','G','R','R','O','O','O','P'],
      ['G','G','R','R','R','O','P','P','P'],
      ['B','B','B','B','B','P','P','P','P'],
      ['B','B','B','B','B','P','P','P','P'],
    ],
  },
];
