import {FlowLevel} from './types';

export const LEVELS: FlowLevel[] = [

  {
    id: 1, title: 'First Flow', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,0], to:[2,1]},
      {key:'B', from:[1,1], to:[2,3]},
      {key:'G', from:[3,3], to:[2,0]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','B','B','B','G'],
      ['G','R','R','B','G'],
      ['R','R','R','G','G'],
      ['R','R','R','G','G'],
    ],
  },

  {
    id: 2, title: 'Two Lines', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,4], to:[1,0]},
      {key:'B', from:[0,0], to:[0,3]},
      {key:'G', from:[1,3], to:[0,4]},
    ],
    solution: [
      ['B','B','B','B','G'],
      ['R','R','R','G','G'],
      ['R','R','R','G','G'],
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 3, title: 'Corner Turn', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,4], to:[3,3]},
      {key:'B', from:[3,4], to:[4,4]},
      {key:'G', from:[4,3], to:[4,0]},
    ],
    solution: [
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
      ['R','R','R','R','R'],
      ['R','R','R','R','B'],
      ['G','G','G','G','B'],
    ],
  },

  {
    id: 4, title: 'Crossroads', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,0], to:[3,3]},
      {key:'B', from:[2,3], to:[3,1]},
      {key:'G', from:[2,1], to:[0,4]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','G','B','B','B'],
      ['R','G','B','B','B'],
      ['R','B','B','R','R'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 5, title: 'Little Loop', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,0], to:[1,1]},
      {key:'B', from:[1,2], to:[3,2]},
      {key:'G', from:[2,2], to:[0,4]},
    ],
    solution: [
      ['R','R','B','B','G'],
      ['R','R','B','B','G'],
      ['R','G','G','B','G'],
      ['R','G','B','B','G'],
      ['R','G','G','G','G'],
    ],
  },

  {
    id: 6, title: 'Side Step', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[4,2], to:[1,2]},
      {key:'B', from:[1,1], to:[3,2]},
      {key:'G', from:[3,3], to:[2,4]},
    ],
    solution: [
      ['R','R','R','R','R'],
      ['R','B','R','R','R'],
      ['R','B','R','R','G'],
      ['R','B','B','G','G'],
      ['R','R','R','G','G'],
    ],
  },

  {
    id: 7, title: 'Twin Paths', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[1,1], to:[4,0]},
      {key:'B', from:[3,0], to:[3,2]},
      {key:'G', from:[2,2], to:[2,4]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','R','R','R','G'],
      ['G','G','G','R','G'],
      ['B','B','B','R','R'],
      ['R','R','R','R','R'],
    ],
  },

  {
    id: 8, title: 'Zig Zag', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[1,1], to:[1,3]},
      {key:'B', from:[0,3], to:[1,0]},
      {key:'G', from:[0,0], to:[2,2]},
    ],
    solution: [
      ['G','G','G','B','B'],
      ['B','R','G','R','B'],
      ['B','R','G','R','B'],
      ['B','R','R','R','B'],
      ['B','B','B','B','B'],
    ],
  },

  {
    id: 9, title: 'Box In', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,2], to:[1,2]},
      {key:'B', from:[0,2], to:[4,4]},
      {key:'G', from:[3,4], to:[3,1]},
    ],
    solution: [
      ['B','B','B','G','G'],
      ['B','R','R','G','G'],
      ['B','R','R','G','G'],
      ['B','G','G','G','G'],
      ['B','B','B','B','B'],
    ],
  },

  {
    id: 10, title: 'Five Ways', difficulty: 'easy', gridSize: 5,
    dots: [
      {key:'R', from:[2,0], to:[3,1]},
      {key:'B', from:[3,0], to:[1,1]},
      {key:'G', from:[1,0], to:[3,4]},
      {key:'Y', from:[4,4], to:[1,3]},
    ],
    solution: [
      ['G','G','G','G','G'],
      ['G','B','B','Y','G'],
      ['R','R','B','Y','G'],
      ['B','R','B','Y','G'],
      ['B','B','B','Y','Y'],
    ],
  },

  {
    id: 11, title: 'River Bend', difficulty: 'easy', gridSize: 6,
    dots: [
      {key:'R', from:[4,5], to:[4,2]},
      {key:'B', from:[4,3], to:[3,3]},
      {key:'G', from:[3,2], to:[4,0]},
      {key:'Y', from:[3,0], to:[1,4]},
      {key:'O', from:[1,3], to:[2,2]},
    ],
    solution: [
      ['Y','Y','Y','Y','Y','Y'],
      ['Y','O','O','O','Y','Y'],
      ['Y','O','O','B','B','B'],
      ['Y','G','G','B','B','B'],
      ['G','G','R','B','B','R'],
      ['G','G','R','R','R','R'],
    ],
  },

  {
    id: 12, title: 'Tangle', difficulty: 'easy', gridSize: 6,
    dots: [
      {key:'R', from:[0,5], to:[1,4]},
      {key:'B', from:[0,4], to:[0,1]},
      {key:'G', from:[0,0], to:[1,0]},
      {key:'Y', from:[2,0], to:[5,2]},
      {key:'O', from:[5,3], to:[1,3]},
    ],
    solution: [
      ['G','B','B','B','B','R'],
      ['G','B','B','O','R','R'],
      ['Y','B','B','O','R','R'],
      ['Y','Y','Y','O','R','R'],
      ['Y','Y','Y','O','R','R'],
      ['Y','Y','Y','O','R','R'],
    ],
  },

  {
    id: 13, title: 'Knot', difficulty: 'easy', gridSize: 6,
    dots: [
      {key:'R', from:[5,0], to:[0,0]},
      {key:'B', from:[0,1], to:[4,2]},
      {key:'G', from:[4,1], to:[5,4]},
      {key:'Y', from:[5,5], to:[2,4]},
      {key:'O', from:[2,5], to:[3,3]},
    ],
    solution: [
      ['R','B','O','O','O','O'],
      ['R','B','O','O','O','O'],
      ['R','B','O','O','Y','O'],
      ['R','B','B','O','Y','Y'],
      ['R','G','B','G','G','Y'],
      ['R','G','G','G','G','Y'],
    ],
  },

  {
    id: 14, title: 'Switchback', difficulty: 'easy', gridSize: 6,
    dots: [
      {key:'R', from:[2,0], to:[4,1]},
      {key:'B', from:[3,1], to:[4,3]},
      {key:'G', from:[4,2], to:[3,4]},
      {key:'Y', from:[3,5], to:[0,4]},
      {key:'O', from:[0,3], to:[1,0]},
    ],
    solution: [
      ['O','O','O','O','Y','Y'],
      ['O','O','O','O','Y','Y'],
      ['R','O','O','O','Y','Y'],
      ['R','B','B','B','G','Y'],
      ['R','R','G','B','G','G'],
      ['R','R','G','G','G','G'],
    ],
  },

  {
    id: 15, title: 'Detour', difficulty: 'easy', gridSize: 6,
    dots: [
      {key:'R', from:[2,3], to:[3,1]},
      {key:'B', from:[2,1], to:[4,4]},
      {key:'G', from:[3,4], to:[0,2]},
      {key:'Y', from:[0,1], to:[1,0]},
      {key:'O', from:[1,1], to:[1,3]},
    ],
    solution: [
      ['Y','Y','G','G','G','G'],
      ['Y','O','O','O','G','G'],
      ['B','B','R','R','G','G'],
      ['B','R','R','R','G','G'],
      ['B','R','R','R','B','B'],
      ['B','B','B','B','B','B'],
    ],
  },

  {
    id: 16, title: 'Spiral', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,3], to:[4,5]},
      {key:'B', from:[3,5], to:[2,3]},
      {key:'G', from:[1,3], to:[0,2]},
      {key:'Y', from:[1,2], to:[5,0]},
      {key:'O', from:[4,0], to:[2,1]},
    ],
    solution: [
      ['O','O','G','G','B','B'],
      ['O','O','Y','G','B','B'],
      ['O','O','Y','B','B','B'],
      ['O','O','Y','R','R','B'],
      ['O','O','Y','R','R','R'],
      ['Y','Y','Y','R','R','R'],
    ],
  },

  {
    id: 17, title: 'Weave', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,1], to:[2,2]},
      {key:'B', from:[2,3], to:[3,3]},
      {key:'G', from:[3,4], to:[5,4]},
      {key:'Y', from:[4,4], to:[4,0]},
      {key:'O', from:[3,0], to:[1,4]},
    ],
    solution: [
      ['O','O','O','O','O','O'],
      ['O','O','O','O','O','O'],
      ['O','O','R','B','O','O'],
      ['O','R','R','B','G','G'],
      ['Y','Y','Y','Y','Y','G'],
      ['Y','Y','Y','Y','G','G'],
    ],
  },

  {
    id: 18, title: 'Lattice', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,1], to:[3,2]},
      {key:'B', from:[4,2], to:[5,3]},
      {key:'G', from:[4,3], to:[5,5]},
      {key:'Y', from:[4,5], to:[2,4]},
      {key:'O', from:[3,4], to:[1,1]},
    ],
    solution: [
      ['O','O','O','O','Y','Y'],
      ['O','O','O','O','Y','Y'],
      ['R','R','O','O','Y','Y'],
      ['R','R','R','O','O','Y'],
      ['R','R','B','G','G','Y'],
      ['R','R','B','B','G','G'],
    ],
  },

  {
    id: 19, title: 'Coil', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[1,4], to:[0,5]},
      {key:'B', from:[0,4], to:[0,3]},
      {key:'G', from:[1,3], to:[3,4]},
      {key:'Y', from:[2,4], to:[4,5]},
      {key:'O', from:[5,5], to:[4,1]},
      {key:'P', from:[4,2], to:[2,0]},
    ],
    solution: [
      ['P','P','P','B','B','R'],
      ['P','P','P','G','R','R'],
      ['P','P','P','G','Y','Y'],
      ['O','O','P','G','G','Y'],
      ['O','O','P','G','G','Y'],
      ['O','O','O','O','O','O'],
    ],
  },

  {
    id: 20, title: 'Maze Start', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[3,3], to:[2,2]},
      {key:'B', from:[3,2], to:[1,1]},
      {key:'G', from:[1,2], to:[4,4]},
      {key:'Y', from:[4,3], to:[0,3]},
      {key:'O', from:[0,2], to:[5,1]},
      {key:'P', from:[5,2], to:[4,1]},
    ],
    solution: [
      ['O','O','O','Y','Y','Y'],
      ['O','B','G','G','G','Y'],
      ['O','B','R','R','G','Y'],
      ['O','B','B','R','G','Y'],
      ['O','P','P','Y','G','Y'],
      ['O','O','P','Y','Y','Y'],
    ],
  },

  {
    id: 21, title: 'Crosswind', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,3], to:[0,5]},
      {key:'B', from:[1,5], to:[3,5]},
      {key:'G', from:[4,5], to:[5,5]},
      {key:'Y', from:[5,4], to:[2,3]},
      {key:'O', from:[2,2], to:[0,1]},
      {key:'P', from:[1,1], to:[1,3]},
    ],
    solution: [
      ['O','O','P','P','R','R'],
      ['O','P','P','P','R','B'],
      ['O','O','O','Y','R','B'],
      ['O','O','Y','Y','R','B'],
      ['O','O','Y','R','R','G'],
      ['O','O','Y','Y','Y','G'],
    ],
  },

  {
    id: 22, title: 'Braid', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[2,4], to:[4,2]},
      {key:'B', from:[3,2], to:[3,0]},
      {key:'G', from:[3,1], to:[4,0]},
      {key:'Y', from:[5,0], to:[4,4]},
      {key:'O', from:[3,4], to:[0,0]},
      {key:'P', from:[0,1], to:[0,3]},
    ],
    solution: [
      ['O','P','P','P','O','O'],
      ['O','O','O','O','O','O'],
      ['B','B','B','R','R','O'],
      ['B','G','B','R','O','O'],
      ['G','G','R','R','Y','Y'],
      ['Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 23, title: 'Snarl', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,4], to:[3,4]},
      {key:'B', from:[3,5], to:[5,4]},
      {key:'G', from:[5,3], to:[4,3]},
      {key:'Y', from:[3,3], to:[0,4]},
      {key:'O', from:[0,3], to:[2,1]},
      {key:'P', from:[1,1], to:[4,1]},
    ],
    solution: [
      ['P','P','O','O','Y','Y'],
      ['P','P','O','Y','Y','Y'],
      ['P','O','O','Y','Y','Y'],
      ['P','O','O','Y','R','B'],
      ['P','P','G','G','R','B'],
      ['P','P','G','G','B','B'],
    ],
  },

  {
    id: 24, title: 'Labyrinth', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[4,5], to:[5,4]},
      {key:'B', from:[4,4], to:[2,3]},
      {key:'G', from:[3,3], to:[3,1]},
      {key:'Y', from:[4,1], to:[5,0]},
      {key:'O', from:[4,0], to:[2,0]},
      {key:'P', from:[2,1], to:[2,2]},
    ],
    solution: [
      ['P','P','P','P','B','B'],
      ['P','P','P','P','B','B'],
      ['O','P','P','B','B','B'],
      ['O','G','G','G','B','B'],
      ['O','Y','G','G','B','R'],
      ['Y','Y','G','G','R','R'],
    ],
  },

  {
    id: 25, title: 'Long Haul', difficulty: 'medium', gridSize: 6,
    dots: [
      {key:'R', from:[2,2], to:[3,4]},
      {key:'B', from:[3,3], to:[5,4]},
      {key:'G', from:[5,3], to:[4,2]},
      {key:'Y', from:[3,2], to:[1,4]},
      {key:'O', from:[1,5], to:[0,4]},
      {key:'P', from:[0,3], to:[4,1]},
    ],
    solution: [
      ['P','P','P','P','O','O'],
      ['P','Y','Y','Y','Y','O'],
      ['P','Y','R','R','R','R'],
      ['P','Y','Y','B','R','R'],
      ['P','P','G','B','B','B'],
      ['P','P','G','G','B','B'],
    ],
  },

  {
    id: 26, title: 'Gridlock', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[2,0], to:[0,1]},
      {key:'B', from:[0,2], to:[0,4]},
      {key:'G', from:[1,4], to:[0,6]},
      {key:'Y', from:[1,6], to:[4,4]},
      {key:'O', from:[4,5], to:[5,1]},
    ],
    solution: [
      ['R','R','B','B','B','G','G'],
      ['R','Y','Y','Y','G','G','Y'],
      ['R','Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','Y','O','Y'],
      ['Y','O','O','O','O','O','Y'],
      ['Y','Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 27, title: 'Tight Squeeze', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[4,2], to:[1,2]},
      {key:'B', from:[1,1], to:[0,3]},
      {key:'G', from:[1,3], to:[6,6]},
      {key:'Y', from:[6,5], to:[5,2]},
      {key:'O', from:[6,2], to:[2,0]},
    ],
    solution: [
      ['B','B','B','B','G','G','G'],
      ['B','B','R','G','G','G','G'],
      ['O','R','R','G','G','G','G'],
      ['O','R','R','G','G','G','G'],
      ['O','O','R','G','G','G','G'],
      ['O','O','Y','Y','Y','Y','G'],
      ['O','O','O','Y','Y','Y','G'],
    ],
  },

  {
    id: 28, title: 'Overpass', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[2,2], to:[4,3]},
      {key:'B', from:[5,3], to:[6,2]},
      {key:'G', from:[6,1], to:[2,5]},
      {key:'Y', from:[2,6], to:[3,4]},
      {key:'O', from:[4,4], to:[5,5]},
    ],
    solution: [
      ['G','G','G','G','G','G','G'],
      ['G','G','R','R','G','G','G'],
      ['G','G','R','R','G','G','Y'],
      ['G','G','G','R','Y','Y','Y'],
      ['G','G','G','R','O','O','O'],
      ['G','G','G','B','B','O','O'],
      ['G','G','B','B','B','O','O'],
    ],
  },

  {
    id: 29, title: 'Junction', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[5,5], to:[4,2]},
      {key:'B', from:[3,2], to:[2,5]},
      {key:'G', from:[1,5], to:[0,6]},
      {key:'Y', from:[0,5], to:[2,3]},
      {key:'O', from:[2,2], to:[2,0]},
    ],
    solution: [
      ['O','O','O','O','Y','Y','G'],
      ['O','O','O','O','Y','G','G'],
      ['O','O','O','Y','Y','B','B'],
      ['O','O','B','B','B','B','B'],
      ['O','O','R','R','R','R','R'],
      ['O','O','R','R','R','R','R'],
      ['O','O','R','R','R','R','R'],
    ],
  },

  {
    id: 30, title: 'Crossover', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[5,1], to:[1,4]},
      {key:'B', from:[1,5], to:[4,0]},
      {key:'G', from:[4,1], to:[3,2]},
      {key:'Y', from:[2,2], to:[1,3]},
      {key:'O', from:[2,3], to:[4,2]},
    ],
    solution: [
      ['B','B','B','B','B','B','B'],
      ['B','Y','Y','Y','R','B','B'],
      ['B','Y','Y','O','R','B','B'],
      ['B','G','G','O','R','R','R'],
      ['B','G','O','O','R','R','R'],
      ['R','R','R','R','R','R','R'],
      ['R','R','R','R','R','R','R'],
    ],
  },

  {
    id: 31, title: 'Deep Dive', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[3,3], to:[4,2]},
      {key:'B', from:[4,3], to:[5,1]},
      {key:'G', from:[6,1], to:[2,3]},
      {key:'Y', from:[2,4], to:[1,5]},
      {key:'O', from:[1,4], to:[0,6]},
    ],
    solution: [
      ['G','G','G','G','O','O','O'],
      ['G','G','G','G','O','Y','Y'],
      ['G','G','G','G','Y','Y','Y'],
      ['G','G','R','R','Y','Y','Y'],
      ['G','G','R','B','Y','Y','Y'],
      ['G','B','B','B','B','Y','Y'],
      ['G','G','B','B','B','Y','Y'],
    ],
  },

  {
    id: 32, title: 'Web', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[5,5], to:[2,1]},
      {key:'B', from:[1,1], to:[1,3]},
      {key:'G', from:[2,3], to:[2,6]},
      {key:'Y', from:[1,6], to:[0,2]},
      {key:'O', from:[0,1], to:[4,2]},
    ],
    solution: [
      ['O','O','Y','Y','Y','Y','Y'],
      ['O','B','B','B','G','G','Y'],
      ['O','R','R','G','G','G','G'],
      ['O','R','R','O','O','O','O'],
      ['O','R','O','O','O','O','O'],
      ['O','R','R','R','R','R','O'],
      ['O','O','O','O','O','O','O'],
    ],
  },

  {
    id: 33, title: 'Mesh', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[6,4], to:[4,1]},
      {key:'B', from:[5,1], to:[4,2]},
      {key:'G', from:[4,3], to:[2,3]},
      {key:'Y', from:[2,4], to:[1,5]},
      {key:'O', from:[2,5], to:[0,4]},
    ],
    solution: [
      ['G','G','G','G','O','O','O'],
      ['G','G','G','G','Y','Y','O'],
      ['G','R','R','G','Y','O','O'],
      ['G','R','R','R','R','R','R'],
      ['G','R','B','G','R','R','R'],
      ['G','B','B','G','R','R','R'],
      ['G','G','G','G','R','R','R'],
    ],
  },

  {
    id: 34, title: 'Puzzle Box', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[2,2], to:[3,6]},
      {key:'B', from:[4,6], to:[2,4]},
      {key:'G', from:[3,4], to:[6,4]},
      {key:'Y', from:[6,3], to:[4,3]},
      {key:'O', from:[3,3], to:[6,0]},
    ],
    solution: [
      ['O','O','O','R','R','R','R'],
      ['O','O','O','R','R','R','R'],
      ['O','O','R','R','B','B','R'],
      ['O','O','O','O','G','B','R'],
      ['O','O','O','Y','G','B','B'],
      ['O','O','O','Y','G','B','B'],
      ['O','O','O','Y','G','B','B'],
    ],
  },

  {
    id: 35, title: 'Entangled', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[1,1], to:[0,5]},
      {key:'B', from:[0,4], to:[0,2]},
      {key:'G', from:[0,1], to:[4,1]},
      {key:'Y', from:[3,1], to:[5,4]},
      {key:'O', from:[5,5], to:[4,3]},
      {key:'P', from:[5,3], to:[5,1]},
    ],
    solution: [
      ['G','G','B','B','B','R','R'],
      ['G','R','R','R','R','R','R'],
      ['G','G','G','G','O','O','O'],
      ['Y','Y','G','G','O','O','O'],
      ['Y','G','G','O','O','O','O'],
      ['Y','P','P','P','Y','O','O'],
      ['Y','Y','Y','Y','Y','O','O'],
    ],
  },

  {
    id: 36, title: 'Crisscross', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[3,1], to:[1,1]},
      {key:'B', from:[2,1], to:[1,3]},
      {key:'G', from:[1,2], to:[1,4]},
      {key:'Y', from:[2,4], to:[5,6]},
      {key:'O', from:[4,6], to:[1,5]},
      {key:'P', from:[2,5], to:[5,5]},
    ],
    solution: [
      ['R','R','G','G','G','O','O'],
      ['R','R','G','B','G','O','O'],
      ['R','B','B','B','Y','P','O'],
      ['R','R','R','R','Y','P','O'],
      ['R','R','R','R','Y','P','O'],
      ['R','R','R','Y','Y','P','Y'],
      ['R','R','R','Y','Y','Y','Y'],
    ],
  },

  {
    id: 37, title: 'Convolution', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[2,2], to:[2,5]},
      {key:'B', from:[2,4], to:[1,1]},
      {key:'G', from:[2,1], to:[3,0]},
      {key:'Y', from:[2,0], to:[6,4]},
      {key:'O', from:[6,3], to:[5,2]},
      {key:'P', from:[6,2], to:[4,0]},
    ],
    solution: [
      ['Y','Y','Y','Y','Y','Y','Y'],
      ['Y','B','B','B','Y','Y','Y'],
      ['Y','G','R','B','B','R','Y'],
      ['G','G','R','B','B','R','Y'],
      ['P','P','R','R','R','R','Y'],
      ['P','P','O','O','Y','Y','Y'],
      ['P','P','P','O','Y','Y','Y'],
    ],
  },

  {
    id: 38, title: 'The Gauntlet', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[3,3], to:[4,2]},
      {key:'B', from:[5,2], to:[3,6]},
      {key:'G', from:[2,6], to:[0,5]},
      {key:'Y', from:[0,4], to:[1,0]},
      {key:'O', from:[1,1], to:[2,2]},
      {key:'P', from:[2,1], to:[4,0]},
    ],
    solution: [
      ['Y','Y','Y','Y','Y','G','G'],
      ['Y','O','O','O','O','O','G'],
      ['P','P','O','O','O','O','G'],
      ['P','P','R','R','O','O','B'],
      ['P','P','R','B','B','B','B'],
      ['P','P','B','B','B','B','B'],
      ['P','P','B','B','B','B','B'],
    ],
  },

  {
    id: 39, title: 'Serpentine', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[6,6], to:[6,3]},
      {key:'B', from:[6,2], to:[5,0]},
      {key:'G', from:[5,1], to:[4,4]},
      {key:'Y', from:[4,3], to:[1,6]},
      {key:'O', from:[0,6], to:[0,4]},
      {key:'P', from:[0,3], to:[1,1]},
    ],
    solution: [
      ['P','P','P','P','O','O','O'],
      ['P','P','P','P','P','Y','Y'],
      ['P','P','P','P','P','Y','Y'],
      ['P','P','P','Y','Y','Y','Y'],
      ['P','P','P','Y','G','Y','Y'],
      ['B','G','G','G','G','R','R'],
      ['B','B','B','R','R','R','R'],
    ],
  },

  {
    id: 40, title: 'Big Knot', difficulty: 'medium', gridSize: 7,
    dots: [
      {key:'R', from:[4,2], to:[3,1]},
      {key:'B', from:[3,2], to:[2,1]},
      {key:'G', from:[2,0], to:[0,0]},
      {key:'Y', from:[0,1], to:[0,6]},
      {key:'O', from:[1,6], to:[5,4]},
      {key:'P', from:[4,4], to:[4,6]},
    ],
    solution: [
      ['G','Y','Y','Y','Y','Y','Y'],
      ['G','B','B','O','O','O','O'],
      ['G','B','B','O','P','P','P'],
      ['R','R','B','O','P','P','P'],
      ['R','R','R','O','P','P','P'],
      ['R','R','R','O','O','O','O'],
      ['R','R','R','O','O','O','O'],
    ],
  },

  {
    id: 41, title: 'Floodgate', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[5,5], to:[0,2]},
      {key:'B', from:[0,3], to:[2,5]},
      {key:'G', from:[2,6], to:[5,6]},
      {key:'Y', from:[6,6], to:[4,2]},
      {key:'O', from:[4,1], to:[5,0]},
      {key:'P', from:[6,0], to:[5,3]},
    ],
    solution: [
      ['R','R','R','B','B','B','B'],
      ['R','R','R','B','B','B','B'],
      ['R','R','R','R','R','B','G'],
      ['R','R','R','R','R','R','G'],
      ['O','O','Y','Y','Y','R','G'],
      ['O','P','P','P','Y','R','G'],
      ['P','P','P','P','Y','Y','Y'],
    ],
  },

  {
    id: 42, title: 'Conduit', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[3,3], to:[3,5]},
      {key:'B', from:[4,5], to:[5,3]},
      {key:'G', from:[5,4], to:[5,2]},
      {key:'Y', from:[4,2], to:[2,1]},
      {key:'O', from:[2,0], to:[0,4]},
      {key:'P', from:[1,4], to:[5,5]},
    ],
    solution: [
      ['O','O','O','O','O','P','P'],
      ['O','Y','Y','Y','P','P','P'],
      ['O','Y','Y','Y','P','P','P'],
      ['Y','Y','Y','R','R','R','P'],
      ['Y','Y','Y','B','B','B','P'],
      ['Y','Y','G','B','G','P','P'],
      ['Y','Y','G','G','G','P','P'],
    ],
  },

  {
    id: 43, title: 'Plexus', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[6,2], to:[5,1]},
      {key:'B', from:[6,1], to:[2,5]},
      {key:'G', from:[1,5], to:[3,4]},
      {key:'Y', from:[3,3], to:[4,6]},
      {key:'O', from:[5,6], to:[5,4]},
      {key:'P', from:[5,3], to:[6,6]},
    ],
    solution: [
      ['B','B','B','B','G','G','G'],
      ['B','B','B','B','G','G','G'],
      ['B','B','B','B','B','B','G'],
      ['B','Y','Y','Y','G','G','G'],
      ['B','Y','Y','Y','Y','Y','Y'],
      ['B','R','R','P','O','O','O'],
      ['B','B','R','P','P','P','P'],
    ],
  },

  {
    id: 44, title: 'Quagmire', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[2,4], to:[3,5]},
      {key:'B', from:[4,5], to:[1,5]},
      {key:'G', from:[1,4], to:[1,2]},
      {key:'Y', from:[1,3], to:[4,4]},
      {key:'O', from:[5,4], to:[6,2]},
      {key:'P', from:[6,1], to:[5,3]},
      {key:'T', from:[4,3], to:[4,0]},
    ],
    solution: [
      ['G','G','G','G','G','B','B'],
      ['G','G','G','Y','G','B','B'],
      ['G','G','G','Y','R','R','B'],
      ['G','G','G','Y','Y','R','B'],
      ['T','T','T','T','Y','B','B'],
      ['P','P','P','P','O','O','O'],
      ['P','P','O','O','O','O','O'],
    ],
  },

  {
    id: 45, title: 'The Weaver', difficulty: 'hard', gridSize: 7,
    dots: [
      {key:'R', from:[3,5], to:[6,2]},
      {key:'B', from:[6,1], to:[5,0]},
      {key:'G', from:[4,0], to:[5,2]},
      {key:'Y', from:[4,2], to:[2,2]},
      {key:'O', from:[2,1], to:[3,0]},
      {key:'P', from:[2,0], to:[0,2]},
      {key:'T', from:[0,3], to:[2,6]},
    ],
    solution: [
      ['P','P','P','T','T','T','T'],
      ['P','P','P','T','T','T','T'],
      ['P','O','Y','T','T','T','T'],
      ['O','O','Y','T','T','R','R'],
      ['G','G','Y','R','R','R','R'],
      ['B','G','G','R','R','R','R'],
      ['B','B','R','R','R','R','R'],
    ],
  },

  {
    id: 46, title: 'Gordian', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,0], to:[4,0]},
      {key:'B', from:[5,0], to:[0,0]},
      {key:'G', from:[0,1], to:[3,3]},
      {key:'Y', from:[2,3], to:[0,7]},
      {key:'O', from:[1,7], to:[2,6]},
      {key:'P', from:[2,7], to:[6,4]},
      {key:'T', from:[7,4], to:[4,6]},
      {key:'K', from:[5,6], to:[4,7]},
    ],
    solution: [
      ['B','G','G','G','Y','Y','Y','Y'],
      ['B','B','G','G','Y','O','O','O'],
      ['R','B','G','Y','Y','O','O','P'],
      ['R','B','G','G','P','P','P','P'],
      ['R','B','G','G','P','T','T','K'],
      ['B','B','G','G','P','T','K','K'],
      ['G','G','G','G','P','T','T','T'],
      ['G','G','G','G','T','T','T','T'],
    ],
  },

  {
    id: 47, title: 'Pipework', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,0], to:[1,1]},
      {key:'B', from:[2,1], to:[4,0]},
      {key:'G', from:[5,0], to:[7,5]},
      {key:'Y', from:[6,5], to:[4,3]},
      {key:'O', from:[4,4], to:[3,5]},
      {key:'P', from:[3,6], to:[2,4]},
      {key:'T', from:[1,4], to:[0,2]},
      {key:'K', from:[1,2], to:[3,4]},
    ],
    solution: [
      ['R','R','T','T','T','T','T','T'],
      ['R','R','K','K','T','T','T','T'],
      ['R','B','B','K','P','P','P','P'],
      ['B','B','B','K','K','O','P','P'],
      ['B','Y','Y','Y','O','O','P','P'],
      ['G','Y','Y','Y','Y','Y','Y','Y'],
      ['G','Y','Y','G','G','Y','Y','Y'],
      ['G','G','G','G','G','G','Y','Y'],
    ],
  },

  {
    id: 48, title: 'Grand Maze', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,5], to:[0,3]},
      {key:'B', from:[1,3], to:[0,6]},
      {key:'G', from:[0,7], to:[2,7]},
      {key:'Y', from:[3,7], to:[7,7]},
      {key:'O', from:[7,6], to:[3,1]},
      {key:'P', from:[2,1], to:[1,0]},
      {key:'T', from:[2,0], to:[6,0]},
      {key:'K', from:[7,0], to:[6,1]},
    ],
    solution: [
      ['P','P','P','R','R','R','B','G'],
      ['P','P','P','B','B','R','B','G'],
      ['T','P','O','O','B','B','B','G'],
      ['T','O','O','O','O','O','O','Y'],
      ['T','T','O','O','O','O','O','Y'],
      ['T','T','O','O','O','O','O','Y'],
      ['T','K','O','O','O','O','O','Y'],
      ['K','K','O','O','O','O','O','Y'],
    ],
  },

  {
    id: 49, title: 'Master Flow', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,1], to:[0,2]},
      {key:'B', from:[0,3], to:[2,3]},
      {key:'G', from:[2,4], to:[0,6]},
      {key:'Y', from:[0,7], to:[5,6]},
      {key:'O', from:[4,6], to:[3,0]},
      {key:'P', from:[4,0], to:[4,2]},
      {key:'T', from:[4,3], to:[7,1]},
      {key:'K', from:[7,0], to:[6,1]},
    ],
    solution: [
      ['R','R','R','B','G','G','G','Y'],
      ['R','R','R','B','G','Y','Y','Y'],
      ['R','R','R','B','G','Y','Y','Y'],
      ['O','O','O','O','O','O','O','Y'],
      ['P','P','P','T','O','O','O','Y'],
      ['K','K','T','T','O','O','Y','Y'],
      ['K','K','T','O','O','O','Y','Y'],
      ['K','T','T','O','O','O','Y','Y'],
    ],
  },

  {
    id: 50, title: 'Flow Master', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[6,1], to:[7,6]},
      {key:'B', from:[7,7], to:[2,5]},
      {key:'G', from:[2,6], to:[0,6]},
      {key:'Y', from:[1,6], to:[0,4]},
      {key:'O', from:[1,4], to:[1,0]},
      {key:'P', from:[2,0], to:[3,3]},
      {key:'T', from:[2,3], to:[5,3]},
      {key:'K', from:[5,4], to:[4,0]},
    ],
    solution: [
      ['O','O','O','O','Y','Y','G','G'],
      ['O','O','O','O','O','Y','Y','G'],
      ['P','O','O','T','T','B','G','G'],
      ['P','P','P','P','T','B','B','B'],
      ['K','P','P','T','T','B','B','B'],
      ['K','K','K','T','K','K','B','B'],
      ['R','R','K','K','K','K','B','B'],
      ['R','R','R','R','R','R','R','B'],
    ],
  },

  {
    id: 51, title: 'Fresh Start', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[3,2], to:[2,3]},
      {key:'B', from:[2,2], to:[6,4]},
      {key:'G', from:[6,3], to:[6,6]},
      {key:'Y', from:[7,6], to:[3,7]},
      {key:'O', from:[2,7], to:[0,4]},
      {key:'P', from:[0,3], to:[3,1]},
    ],
    solution: [
      ['P','P','P','P','O','O','O','O'],
      ['P','B','B','B','B','O','O','O'],
      ['P','B','B','R','B','O','O','O'],
      ['P','P','R','R','B','Y','Y','Y'],
      ['B','B','B','B','B','Y','Y','Y'],
      ['B','B','B','G','G','G','G','Y'],
      ['B','B','B','G','B','B','G','Y'],
      ['B','B','B','B','B','B','Y','Y'],
    ],
  },

  {
    id: 52, title: 'Loop Back', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[5,4], to:[0,2]},
      {key:'B', from:[0,1], to:[1,2]},
      {key:'G', from:[2,2], to:[6,2]},
      {key:'Y', from:[6,1], to:[7,6]},
      {key:'O', from:[7,7], to:[0,6]},
      {key:'P', from:[0,5], to:[2,4]},
    ],
    solution: [
      ['B','B','R','R','R','P','O','O'],
      ['B','B','B','R','R','P','P','O'],
      ['B','B','G','R','P','P','P','O'],
      ['Y','Y','G','R','R','P','P','O'],
      ['Y','Y','G','G','R','P','P','O'],
      ['Y','Y','G','G','R','Y','Y','O'],
      ['Y','Y','G','Y','Y','Y','Y','O'],
      ['Y','Y','Y','Y','Y','Y','Y','O'],
    ],
  },

  {
    id: 53, title: 'Twist', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[4,0], to:[7,2]},
      {key:'B', from:[7,3], to:[5,6]},
      {key:'G', from:[6,6], to:[3,1]},
      {key:'Y', from:[3,0], to:[0,1]},
      {key:'O', from:[0,2], to:[3,6]},
      {key:'P', from:[3,7], to:[1,6]},
    ],
    solution: [
      ['Y','Y','O','O','O','O','O','O'],
      ['Y','G','G','G','P','P','P','O'],
      ['Y','G','G','G','P','P','O','O'],
      ['Y','G','G','G','P','P','O','P'],
      ['R','G','G','G','P','P','P','P'],
      ['R','R','R','G','P','P','B','B'],
      ['R','R','R','G','G','G','G','B'],
      ['R','R','R','B','B','B','B','B'],
    ],
  },

  {
    id: 54, title: 'Hairpin', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,0], to:[5,3]},
      {key:'B', from:[6,3], to:[7,4]},
      {key:'G', from:[7,5], to:[2,6]},
      {key:'Y', from:[2,5], to:[6,5]},
      {key:'O', from:[6,4], to:[1,5]},
      {key:'P', from:[1,6], to:[0,5]},
    ],
    solution: [
      ['O','O','O','O','O','P','P','P'],
      ['O','O','O','O','O','O','P','P'],
      ['R','O','O','O','O','Y','G','G'],
      ['R','O','O','O','O','Y','G','G'],
      ['R','O','O','O','O','Y','G','G'],
      ['R','R','R','R','O','Y','Y','G'],
      ['B','B','B','B','O','Y','Y','G'],
      ['B','B','B','B','B','G','G','G'],
    ],
  },

  {
    id: 55, title: 'Cross Lane', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[5,3], to:[1,5]},
      {key:'B', from:[1,6], to:[5,1]},
      {key:'G', from:[4,1], to:[6,3]},
      {key:'Y', from:[6,4], to:[4,4]},
      {key:'O', from:[4,5], to:[6,6]},
      {key:'P', from:[6,5], to:[6,1]},
    ],
    solution: [
      ['B','B','B','B','B','B','B','B'],
      ['B','R','R','R','R','R','B','B'],
      ['B','R','R','R','O','O','O','O'],
      ['B','R','R','R','O','O','O','O'],
      ['B','G','G','R','Y','O','O','O'],
      ['B','B','G','R','Y','O','O','O'],
      ['P','P','G','G','Y','P','O','O'],
      ['P','P','P','P','P','P','O','O'],
    ],
  },

  {
    id: 56, title: 'Ravel', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,2], to:[1,3]},
      {key:'B', from:[2,3], to:[0,1]},
      {key:'G', from:[0,0], to:[3,0]},
      {key:'Y', from:[3,1], to:[4,4]},
      {key:'O', from:[4,5], to:[7,7]},
      {key:'P', from:[7,6], to:[6,1]},
    ],
    solution: [
      ['G','B','B','B','B','B','B','B'],
      ['G','G','R','R','B','B','B','B'],
      ['G','G','R','B','B','B','B','B'],
      ['G','Y','Y','B','B','B','B','B'],
      ['Y','Y','Y','Y','Y','O','O','O'],
      ['Y','Y','Y','Y','P','P','P','O'],
      ['P','P','Y','Y','P','P','P','O'],
      ['P','P','P','P','P','P','P','O'],
    ],
  },

  {
    id: 57, title: 'Threadwork', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,1], to:[0,2]},
      {key:'B', from:[1,2], to:[7,2]},
      {key:'G', from:[7,3], to:[5,4]},
      {key:'Y', from:[5,5], to:[0,5]},
      {key:'O', from:[0,4], to:[1,6]},
      {key:'P', from:[2,6], to:[6,1]},
    ],
    solution: [
      ['R','R','R','O','O','Y','Y','Y'],
      ['R','R','B','O','O','O','O','Y'],
      ['B','B','B','P','P','P','P','Y'],
      ['B','B','B','P','P','P','P','Y'],
      ['B','P','P','P','P','P','P','Y'],
      ['B','P','P','G','G','Y','Y','Y'],
      ['B','P','P','G','G','Y','Y','Y'],
      ['B','B','B','G','G','Y','Y','Y'],
    ],
  },

  {
    id: 58, title: 'Backtrack', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,2], to:[1,5]},
      {key:'B', from:[1,6], to:[5,2]},
      {key:'G', from:[6,2], to:[5,1]},
      {key:'Y', from:[5,0], to:[6,3]},
      {key:'O', from:[5,3], to:[6,5]},
      {key:'P', from:[6,6], to:[3,6]},
    ],
    solution: [
      ['B','B','B','B','B','B','B','B'],
      ['B','B','B','R','R','R','B','B'],
      ['B','B','R','R','R','O','O','O'],
      ['B','B','R','R','R','O','P','O'],
      ['B','B','B','O','O','O','P','O'],
      ['Y','G','B','O','O','O','P','O'],
      ['Y','G','G','Y','O','O','P','O'],
      ['Y','Y','Y','Y','O','O','O','O'],
    ],
  },

  {
    id: 59, title: 'Snake Pit', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,3], to:[1,5]},
      {key:'B', from:[1,6], to:[4,4]},
      {key:'G', from:[5,4], to:[6,7]},
      {key:'Y', from:[6,6], to:[5,5]},
      {key:'O', from:[5,6], to:[7,2]},
      {key:'P', from:[7,3], to:[5,2]},
    ],
    solution: [
      ['O','O','O','O','O','O','O','O'],
      ['O','R','R','R','R','R','B','O'],
      ['O','R','R','R','R','B','B','O'],
      ['O','R','R','R','R','B','B','O'],
      ['O','P','P','P','B','B','B','O'],
      ['O','P','P','P','G','Y','O','O'],
      ['O','O','O','P','G','Y','Y','G'],
      ['O','O','O','P','G','G','G','G'],
    ],
  },

  {
    id: 60, title: 'Tenfold', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[2,3], to:[2,7]},
      {key:'B', from:[1,7], to:[1,0]},
      {key:'G', from:[2,0], to:[6,1]},
      {key:'Y', from:[5,1], to:[3,1]},
      {key:'O', from:[3,2], to:[3,5]},
      {key:'P', from:[4,5], to:[6,7]},
      {key:'T', from:[5,7], to:[4,6]},
    ],
    solution: [
      ['B','B','B','B','B','B','B','B'],
      ['B','B','B','R','R','R','R','B'],
      ['G','B','B','R','O','O','R','R'],
      ['G','Y','O','O','O','O','T','T'],
      ['G','Y','P','P','P','P','T','T'],
      ['G','Y','P','P','P','P','P','T'],
      ['G','G','P','P','P','P','P','P'],
      ['G','G','P','P','P','P','P','P'],
    ],
  },

  {
    id: 61, title: 'Crossfire', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[5,5], to:[2,6]},
      {key:'B', from:[2,5], to:[0,7]},
      {key:'G', from:[0,6], to:[0,4]},
      {key:'Y', from:[1,4], to:[1,2]},
      {key:'O', from:[2,2], to:[5,1]},
      {key:'P', from:[4,1], to:[5,0]},
      {key:'T', from:[6,0], to:[6,5]},
    ],
    solution: [
      ['Y','Y','Y','Y','G','G','G','B'],
      ['Y','Y','Y','Y','Y','B','B','B'],
      ['O','O','O','Y','Y','B','R','R'],
      ['O','O','O','Y','Y','R','R','R'],
      ['P','P','O','O','O','R','T','T'],
      ['P','O','O','O','O','R','T','T'],
      ['T','O','O','O','O','T','T','T'],
      ['T','T','T','T','T','T','T','T'],
    ],
  },

  {
    id: 62, title: 'Meander', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[0,1], to:[0,3]},
      {key:'B', from:[1,3], to:[2,4]},
      {key:'G', from:[2,5], to:[0,4]},
      {key:'Y', from:[0,5], to:[2,6]},
      {key:'O', from:[2,7], to:[5,0]},
      {key:'P', from:[4,0], to:[5,1]},
      {key:'T', from:[6,1], to:[2,0]},
    ],
    solution: [
      ['R','R','R','R','G','Y','Y','Y'],
      ['R','R','R','B','G','G','Y','Y'],
      ['T','R','R','B','B','G','Y','O'],
      ['T','T','T','B','B','O','O','O'],
      ['P','P','T','T','T','O','O','O'],
      ['O','P','T','T','T','O','O','O'],
      ['O','T','T','T','T','O','O','O'],
      ['O','O','O','O','O','O','O','O'],
    ],
  },

  {
    id: 63, title: 'Filigree', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,2], to:[7,0]},
      {key:'B', from:[7,1], to:[3,3]},
      {key:'G', from:[4,3], to:[7,7]},
      {key:'Y', from:[6,7], to:[0,7]},
      {key:'O', from:[0,6], to:[2,6]},
      {key:'P', from:[2,5], to:[5,4]},
      {key:'T', from:[6,4], to:[6,6]},
    ],
    solution: [
      ['R','R','R','R','R','R','O','Y'],
      ['R','R','R','R','R','R','O','Y'],
      ['R','R','B','B','P','P','O','Y'],
      ['R','B','B','B','P','P','P','Y'],
      ['R','B','G','G','P','P','P','Y'],
      ['R','B','G','G','P','T','T','Y'],
      ['R','B','G','G','T','T','T','Y'],
      ['R','B','G','G','G','G','G','G'],
    ],
  },

  {
    id: 64, title: 'Pretzel', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[0,7], to:[0,5]},
      {key:'B', from:[0,4], to:[0,1]},
      {key:'G', from:[0,0], to:[3,1]},
      {key:'Y', from:[3,2], to:[6,3]},
      {key:'O', from:[5,3], to:[4,4]},
      {key:'P', from:[4,5], to:[4,7]},
      {key:'T', from:[5,7], to:[5,5]},
    ],
    solution: [
      ['G','B','B','B','B','R','R','R'],
      ['G','G','Y','Y','Y','Y','Y','Y'],
      ['G','G','Y','Y','Y','Y','Y','Y'],
      ['G','G','Y','Y','Y','Y','Y','Y'],
      ['Y','Y','Y','Y','O','P','P','P'],
      ['Y','Y','Y','O','O','T','T','T'],
      ['Y','Y','Y','Y','T','T','T','T'],
      ['Y','Y','Y','Y','T','T','T','T'],
    ],
  },

  {
    id: 65, title: 'Long Game', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,5], to:[4,7]},
      {key:'B', from:[5,7], to:[7,7]},
      {key:'G', from:[7,6], to:[2,3]},
      {key:'Y', from:[3,3], to:[4,1]},
      {key:'O', from:[3,1], to:[7,0]},
      {key:'P', from:[7,1], to:[6,4]},
      {key:'T', from:[6,5], to:[6,3]},
    ],
    solution: [
      ['O','O','G','G','G','R','R','R'],
      ['O','O','G','G','G','R','R','R'],
      ['O','O','O','G','G','G','R','R'],
      ['O','O','O','Y','G','G','R','R'],
      ['O','Y','Y','Y','G','G','R','R'],
      ['O','O','P','P','P','G','G','B'],
      ['O','O','P','T','P','T','G','B'],
      ['O','P','P','T','T','T','G','B'],
    ],
  },

  {
    id: 66, title: 'Deadlock', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[6,3], to:[5,1]},
      {key:'B', from:[5,0], to:[6,5]},
      {key:'G', from:[7,5], to:[4,3]},
      {key:'Y', from:[5,3], to:[2,0]},
      {key:'O', from:[1,0], to:[3,7]},
      {key:'P', from:[2,7], to:[0,4]},
      {key:'T', from:[0,3], to:[2,4]},
    ],
    solution: [
      ['O','O','T','T','P','P','P','P'],
      ['O','O','T','T','T','O','O','P'],
      ['Y','O','T','T','T','O','O','P'],
      ['Y','O','O','O','O','O','O','O'],
      ['Y','Y','Y','G','G','G','G','G'],
      ['B','R','Y','Y','B','B','G','G'],
      ['B','R','R','R','B','B','G','G'],
      ['B','B','B','B','B','G','G','G'],
    ],
  },

  {
    id: 67, title: 'Squeeze Play', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[0,7], to:[0,5]},
      {key:'B', from:[0,4], to:[3,7]},
      {key:'G', from:[4,7], to:[7,6]},
      {key:'Y', from:[7,5], to:[1,1]},
      {key:'O', from:[2,1], to:[4,4]},
      {key:'P', from:[5,4], to:[3,0]},
      {key:'T', from:[2,0], to:[0,2]},
    ],
    solution: [
      ['T','T','T','B','B','R','R','R'],
      ['T','Y','Y','B','B','B','R','R'],
      ['T','O','Y','B','B','B','B','B'],
      ['P','O','Y','Y','Y','Y','Y','B'],
      ['P','O','O','O','O','Y','Y','G'],
      ['P','P','P','P','P','Y','G','G'],
      ['P','P','P','P','P','Y','G','G'],
      ['P','P','P','P','P','Y','G','G'],
    ],
  },

  {
    id: 68, title: 'Flyover', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,0], to:[3,0]},
      {key:'B', from:[4,0], to:[0,7]},
      {key:'G', from:[1,7], to:[4,5]},
      {key:'Y', from:[4,4], to:[5,7]},
      {key:'O', from:[6,7], to:[5,0]},
      {key:'P', from:[6,0], to:[7,1]},
      {key:'T', from:[6,1], to:[7,5]},
    ],
    solution: [
      ['R','R','R','R','B','B','B','B'],
      ['R','R','R','R','B','G','G','G'],
      ['R','R','R','R','B','G','G','G'],
      ['R','R','R','B','B','G','G','G'],
      ['B','B','B','B','Y','G','G','G'],
      ['O','O','O','O','Y','Y','Y','Y'],
      ['P','T','T','O','O','O','O','O'],
      ['P','P','T','T','T','T','O','O'],
    ],
  },

  {
    id: 69, title: 'Interchange', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[3,2], to:[2,3]},
      {key:'B', from:[2,2], to:[0,6]},
      {key:'G', from:[0,7], to:[4,2]},
      {key:'Y', from:[5,2], to:[7,2]},
      {key:'O', from:[7,3], to:[5,3]},
      {key:'P', from:[5,4], to:[7,6]},
      {key:'T', from:[7,7], to:[4,5]},
      {key:'K', from:[5,5], to:[4,6]},
    ],
    solution: [
      ['B','B','B','B','B','B','B','G'],
      ['B','B','B','B','B','B','B','G'],
      ['B','B','B','R','G','G','G','G'],
      ['Y','Y','R','R','G','T','T','T'],
      ['Y','Y','G','G','G','T','K','T'],
      ['Y','Y','Y','O','P','K','K','T'],
      ['Y','Y','Y','O','P','P','P','T'],
      ['Y','Y','Y','O','P','P','P','T'],
    ],
  },

  {
    id: 70, title: 'Tangent', difficulty: 'hard', gridSize: 8,
    dots: [
      {key:'R', from:[1,7], to:[2,6]},
      {key:'B', from:[2,7], to:[6,5]},
      {key:'G', from:[5,5], to:[2,5]},
      {key:'Y', from:[2,4], to:[1,5]},
      {key:'O', from:[0,5], to:[0,2]},
      {key:'P', from:[1,2], to:[6,1]},
      {key:'T', from:[5,1], to:[4,2]},
      {key:'K', from:[5,2], to:[4,3]},
    ],
    solution: [
      ['P','P','O','O','O','O','R','R'],
      ['P','P','P','Y','Y','Y','R','R'],
      ['P','P','P','Y','Y','G','R','B'],
      ['P','P','P','Y','Y','G','B','B'],
      ['P','T','T','K','K','G','B','B'],
      ['P','T','K','K','K','G','B','B'],
      ['P','P','K','K','K','B','B','B'],
      ['P','P','K','K','K','B','B','B'],
    ],
  },

  {
    id: 71, title: 'Abyss', difficulty: 'hard', gridSize: 9,
    dots: [
      {key:'R', from:[6,0], to:[1,0]},
      {key:'B', from:[0,0], to:[3,1]},
      {key:'G', from:[4,1], to:[6,2]},
      {key:'Y', from:[7,2], to:[8,3]},
      {key:'O', from:[7,3], to:[7,6]},
      {key:'P', from:[7,7], to:[5,4]},
      {key:'T', from:[6,4], to:[1,7]},
      {key:'K', from:[2,7], to:[7,8]},
      {key:'N', from:[8,8], to:[8,4]},
    ],
    solution: [
      ['B','B','T','T','T','T','T','T','T'],
      ['R','B','T','K','K','T','T','T','T'],
      ['R','B','T','K','K','K','K','K','K'],
      ['R','B','T','K','K','K','K','K','K'],
      ['R','G','T','K','K','K','K','K','K'],
      ['R','G','T','T','P','P','P','P','K'],
      ['R','G','G','T','T','O','O','P','K'],
      ['Y','Y','Y','O','O','O','O','P','K'],
      ['Y','Y','Y','Y','N','N','N','N','N'],
    ],
  },

  {
    id: 72, title: 'Cobweb', difficulty: 'hard', gridSize: 9,
    dots: [
      {key:'R', from:[4,8], to:[8,7]},
      {key:'B', from:[8,6], to:[8,2]},
      {key:'G', from:[8,1], to:[5,2]},
      {key:'Y', from:[4,2], to:[7,4]},
      {key:'O', from:[7,5], to:[6,6]},
      {key:'P', from:[6,5], to:[0,6]},
      {key:'T', from:[0,5], to:[5,1]},
      {key:'K', from:[4,1], to:[1,2]},
      {key:'N', from:[1,3], to:[1,7]},
    ],
    solution: [
      ['T','T','T','T','T','T','P','P','P'],
      ['T','T','K','N','N','N','N','N','P'],
      ['T','T','K','N','N','N','P','P','P'],
      ['T','K','K','N','N','N','P','P','P'],
      ['T','K','Y','Y','N','N','P','R','R'],
      ['T','T','G','Y','Y','P','P','R','R'],
      ['T','T','G','G','Y','P','O','O','R'],
      ['G','G','G','G','Y','O','O','O','R'],
      ['G','G','B','B','B','B','B','R','R'],
    ],
  },

  {
    id: 73, title: 'Network', difficulty: 'hard', gridSize: 9,
    dots: [
      {key:'R', from:[2,2], to:[5,4]},
      {key:'B', from:[5,5], to:[6,0]},
      {key:'G', from:[7,0], to:[8,2]},
      {key:'Y', from:[8,3], to:[7,5]},
      {key:'O', from:[8,5], to:[6,6]},
      {key:'P', from:[5,6], to:[4,7]},
      {key:'T', from:[5,7], to:[4,8]},
      {key:'K', from:[3,8], to:[1,2]},
      {key:'N', from:[0,2], to:[1,1]},
    ],
    solution: [
      ['N','N','N','K','K','K','K','K','K'],
      ['N','N','K','K','K','K','K','K','K'],
      ['B','B','R','R','K','K','K','K','K'],
      ['B','B','B','R','R','R','K','K','K'],
      ['B','B','B','R','R','R','P','P','T'],
      ['B','B','B','R','R','B','P','T','T'],
      ['B','B','B','B','B','B','O','O','O'],
      ['G','B','B','B','Y','Y','O','O','O'],
      ['G','G','G','Y','Y','O','O','O','O'],
    ],
  },

  {
    id: 74, title: 'Brainbox', difficulty: 'hard', gridSize: 9,
    dots: [
      {key:'R', from:[8,4], to:[8,8]},
      {key:'B', from:[7,8], to:[0,7]},
      {key:'G', from:[0,6], to:[0,3]},
      {key:'Y', from:[1,3], to:[0,2]},
      {key:'O', from:[0,1], to:[2,0]},
      {key:'P', from:[3,0], to:[4,5]},
      {key:'T', from:[4,4], to:[1,5]},
      {key:'K', from:[1,6], to:[3,7]},
      {key:'N', from:[4,7], to:[7,7]},
    ],
    solution: [
      ['O','O','Y','G','G','G','G','B','B'],
      ['O','Y','Y','Y','Y','T','K','K','B'],
      ['O','Y','Y','Y','Y','T','T','K','B'],
      ['P','P','P','P','P','P','T','K','B'],
      ['T','T','T','T','T','P','T','N','B'],
      ['T','T','T','T','T','T','T','N','B'],
      ['T','T','T','T','N','N','N','N','B'],
      ['T','T','T','T','N','N','N','N','B'],
      ['T','T','T','T','R','R','R','R','R'],
    ],
  },

  {
    id: 75, title: 'Twisted', difficulty: 'hard', gridSize: 9,
    dots: [
      {key:'R', from:[1,7], to:[7,8]},
      {key:'B', from:[6,8], to:[2,7]},
      {key:'G', from:[3,7], to:[1,8]},
      {key:'Y', from:[0,8], to:[0,3]},
      {key:'O', from:[0,2], to:[0,0]},
      {key:'P', from:[1,0], to:[1,2]},
      {key:'T', from:[2,2], to:[8,0]},
      {key:'K', from:[8,1], to:[8,3]},
      {key:'N', from:[8,4], to:[5,1]},
    ],
    solution: [
      ['O','O','O','Y','Y','Y','Y','Y','Y'],
      ['P','P','P','Y','Y','R','R','R','G'],
      ['P','P','T','Y','Y','R','B','B','G'],
      ['P','P','T','Y','Y','R','B','G','G'],
      ['T','T','T','N','N','R','B','B','B'],
      ['T','N','N','N','N','R','B','B','B'],
      ['T','T','K','K','N','R','R','R','B'],
      ['T','T','K','K','N','N','N','R','R'],
      ['T','K','K','K','N','N','N','R','R'],
    ],
  },

  {
    id: 76, title: 'Hatchwork', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[8,4], to:[7,2]},
      {key:'B', from:[6,2], to:[2,3]},
      {key:'G', from:[3,3], to:[0,6]},
      {key:'Y', from:[0,7], to:[1,8]},
      {key:'O', from:[2,8], to:[8,8]},
      {key:'P', from:[8,7], to:[3,5]},
      {key:'T', from:[3,6], to:[1,7]},
    ],
    solution: [
      ['B','B','B','B','B','G','G','Y','Y'],
      ['B','B','B','B','B','G','G','T','Y'],
      ['B','B','B','B','G','G','G','T','O'],
      ['R','R','B','G','G','P','T','T','O'],
      ['R','R','B','G','G','P','P','P','O'],
      ['R','R','B','B','B','P','P','P','O'],
      ['R','R','B','B','B','P','O','O','O'],
      ['R','R','R','R','R','P','O','O','O'],
      ['R','R','R','R','R','P','P','P','O'],
    ],
  },

  {
    id: 77, title: 'Spaghetti', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,1], to:[3,1]},
      {key:'B', from:[4,1], to:[3,4]},
      {key:'G', from:[3,5], to:[8,6]},
      {key:'Y', from:[7,6], to:[8,7]},
      {key:'O', from:[8,8], to:[6,8]},
      {key:'P', from:[5,8], to:[0,7]},
      {key:'T', from:[0,6], to:[7,3]},
    ],
    solution: [
      ['T','T','T','T','T','T','T','P','P'],
      ['T','R','R','T','T','P','P','P','P'],
      ['T','R','R','T','T','P','P','P','P'],
      ['T','R','B','B','B','G','P','P','P'],
      ['T','B','B','B','B','G','P','P','P'],
      ['T','B','B','B','B','G','P','P','P'],
      ['T','T','T','T','T','G','P','P','O'],
      ['T','T','T','T','T','G','Y','Y','O'],
      ['T','T','T','T','T','G','G','Y','O'],
    ],
  },

  {
    id: 78, title: 'The Trial', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,4], to:[8,6]},
      {key:'B', from:[8,7], to:[6,7]},
      {key:'G', from:[6,8], to:[0,6]},
      {key:'Y', from:[0,5], to:[0,3]},
      {key:'O', from:[0,2], to:[2,1]},
      {key:'P', from:[3,1], to:[6,0]},
      {key:'T', from:[6,1], to:[1,1]},
    ],
    solution: [
      ['O','O','O','Y','Y','Y','G','G','G'],
      ['O','T','T','T','Y','Y','G','G','G'],
      ['O','O','T','T','T','T','G','G','G'],
      ['P','P','T','T','T','T','G','G','G'],
      ['P','P','T','T','T','T','B','B','G'],
      ['P','P','T','R','R','R','B','B','G'],
      ['P','T','T','R','R','R','B','B','G'],
      ['R','R','R','R','R','R','B','B','B'],
      ['R','R','R','R','R','R','R','B','B'],
    ],
  },

  {
    id: 79, title: 'Sidewinder', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[2,6], to:[2,0]},
      {key:'B', from:[2,1], to:[8,1]},
      {key:'G', from:[7,1], to:[4,4]},
      {key:'Y', from:[5,4], to:[8,3]},
      {key:'O', from:[7,3], to:[7,8]},
      {key:'P', from:[7,7], to:[3,4]},
      {key:'T', from:[3,3], to:[1,3]},
    ],
    solution: [
      ['R','R','R','R','R','R','R','R','R'],
      ['R','R','R','T','T','T','R','R','R'],
      ['R','B','B','T','T','T','R','R','R'],
      ['B','B','B','T','P','P','P','P','P'],
      ['B','G','G','G','G','P','P','P','P'],
      ['B','G','G','G','Y','O','O','P','P'],
      ['B','G','Y','Y','Y','O','O','P','P'],
      ['B','G','Y','O','O','O','O','P','O'],
      ['B','B','Y','Y','O','O','O','O','O'],
    ],
  },

  {
    id: 80, title: 'Hard Knot', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[0,2], to:[0,4]},
      {key:'B', from:[0,5], to:[2,7]},
      {key:'G', from:[2,8], to:[3,0]},
      {key:'Y', from:[4,0], to:[3,2]},
      {key:'O', from:[3,1], to:[4,4]},
      {key:'P', from:[5,4], to:[8,7]},
      {key:'T', from:[8,6], to:[7,7]},
    ],
    solution: [
      ['G','G','R','R','R','B','B','B','B'],
      ['G','G','G','G','G','G','G','B','B'],
      ['G','O','O','O','O','G','G','B','G'],
      ['G','O','Y','O','O','G','G','G','G'],
      ['Y','Y','Y','O','O','G','G','G','G'],
      ['Y','Y','Y','Y','P','G','G','P','P'],
      ['Y','Y','Y','Y','P','P','P','P','P'],
      ['Y','Y','Y','Y','T','T','T','T','P'],
      ['Y','Y','Y','Y','T','T','T','P','P'],
    ],
  },

  {
    id: 81, title: 'Sluice', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[5,5], to:[6,7]},
      {key:'B', from:[7,7], to:[1,7]},
      {key:'G', from:[1,8], to:[0,5]},
      {key:'Y', from:[1,5], to:[0,3]},
      {key:'O', from:[0,2], to:[5,1]},
      {key:'P', from:[4,1], to:[1,2]},
      {key:'T', from:[1,3], to:[8,0]},
    ],
    solution: [
      ['O','O','O','Y','Y','G','G','G','G'],
      ['O','P','P','T','Y','Y','B','B','G'],
      ['O','P','T','T','Y','Y','B','B','B'],
      ['O','P','T','T','T','T','B','B','B'],
      ['O','P','T','T','T','T','B','B','B'],
      ['O','O','T','T','T','R','B','B','B'],
      ['O','O','T','T','T','R','R','R','B'],
      ['T','T','T','T','T','R','R','B','B'],
      ['T','T','T','T','T','R','R','B','B'],
    ],
  },

  {
    id: 82, title: 'Channel', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,4], to:[7,1]},
      {key:'B', from:[6,1], to:[7,0]},
      {key:'G', from:[8,0], to:[8,2]},
      {key:'Y', from:[8,3], to:[3,2]},
      {key:'O', from:[2,2], to:[0,3]},
      {key:'P', from:[0,4], to:[1,7]},
      {key:'T', from:[0,7], to:[1,5]},
    ],
    solution: [
      ['O','O','O','O','P','P','P','T','T'],
      ['O','O','O','T','T','T','P','P','T'],
      ['Y','Y','O','T','T','T','T','T','T'],
      ['Y','Y','Y','T','T','Y','Y','T','T'],
      ['Y','Y','Y','Y','Y','Y','Y','Y','Y'],
      ['B','B','B','B','R','R','Y','Y','Y'],
      ['B','B','B','B','R','R','Y','Y','Y'],
      ['B','R','R','R','R','R','Y','Y','Y'],
      ['G','G','G','Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 83, title: 'Nexus', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[7,5], to:[7,2]},
      {key:'B', from:[7,1], to:[6,2]},
      {key:'G', from:[6,3], to:[1,0]},
      {key:'Y', from:[0,0], to:[0,3]},
      {key:'O', from:[0,4], to:[2,7]},
      {key:'P', from:[2,8], to:[3,0]},
      {key:'T', from:[2,0], to:[2,4]},
    ],
    solution: [
      ['Y','Y','Y','Y','O','O','O','O','O'],
      ['G','G','G','G','G','G','O','O','O'],
      ['T','T','G','G','T','G','O','O','P'],
      ['P','T','T','T','T','G','G','G','P'],
      ['P','T','T','G','G','G','G','G','P'],
      ['P','T','T','G','G','G','G','G','P'],
      ['P','B','B','G','R','R','G','G','P'],
      ['P','B','R','R','R','R','G','G','P'],
      ['P','P','P','P','P','P','P','P','P'],
    ],
  },

  {
    id: 84, title: 'Mire', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,7], to:[5,8]},
      {key:'B', from:[6,8], to:[8,6]},
      {key:'G', from:[8,5], to:[6,6]},
      {key:'Y', from:[6,5], to:[1,5]},
      {key:'O', from:[0,5], to:[4,0]},
      {key:'P', from:[4,1], to:[5,2]},
      {key:'T', from:[5,3], to:[4,2]},
    ],
    solution: [
      ['O','O','O','O','O','O','R','R','R'],
      ['O','O','O','O','O','Y','R','R','R'],
      ['O','Y','Y','Y','Y','Y','R','R','R'],
      ['O','Y','Y','Y','Y','Y','Y','R','R'],
      ['O','P','T','T','Y','Y','Y','R','R'],
      ['P','P','P','T','Y','Y','G','G','R'],
      ['P','P','P','G','G','Y','G','G','B'],
      ['G','G','G','G','G','G','G','G','B'],
      ['G','G','G','G','G','G','B','B','B'],
    ],
  },

  {
    id: 85, title: 'Loomwork', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[3,3], to:[0,3]},
      {key:'B', from:[0,4], to:[4,8]},
      {key:'G', from:[5,8], to:[6,6]},
      {key:'Y', from:[6,5], to:[8,3]},
      {key:'O', from:[8,2], to:[8,0]},
      {key:'P', from:[7,0], to:[7,3]},
      {key:'T', from:[6,3], to:[3,2]},
      {key:'K', from:[2,2], to:[1,1]},
    ],
    solution: [
      ['K','K','R','R','B','B','B','B','B'],
      ['K','K','R','R','R','R','B','B','B'],
      ['K','K','K','R','R','R','B','B','B'],
      ['K','K','T','R','R','R','B','B','B'],
      ['T','T','T','Y','Y','Y','B','B','B'],
      ['T','T','T','Y','Y','Y','B','B','G'],
      ['P','P','T','T','Y','Y','G','G','G'],
      ['P','P','P','P','Y','Y','G','G','G'],
      ['O','O','O','Y','Y','Y','G','G','G'],
    ],
  },

  {
    id: 86, title: 'Tangle Knot', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[8,4], to:[3,1]},
      {key:'B', from:[4,1], to:[2,1]},
      {key:'G', from:[1,1], to:[0,0]},
      {key:'Y', from:[0,1], to:[4,3]},
      {key:'O', from:[4,4], to:[6,5]},
      {key:'P', from:[7,5], to:[3,6]},
      {key:'T', from:[3,5], to:[2,7]},
      {key:'K', from:[3,7], to:[1,7]},
    ],
    solution: [
      ['G','Y','Y','Y','T','T','T','K','K'],
      ['G','G','Y','Y','T','T','T','K','K'],
      ['B','B','Y','Y','T','T','T','T','K'],
      ['B','R','R','Y','T','T','P','K','K'],
      ['B','B','R','Y','O','O','P','P','P'],
      ['R','R','R','O','O','O','P','P','P'],
      ['R','R','R','O','O','O','P','P','P'],
      ['R','R','R','R','R','P','P','P','P'],
      ['R','R','R','R','R','P','P','P','P'],
    ],
  },

  {
    id: 87, title: 'Plumbline', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[8,8], to:[7,7]},
      {key:'B', from:[8,7], to:[6,6]},
      {key:'G', from:[5,6], to:[8,3]},
      {key:'Y', from:[8,2], to:[7,0]},
      {key:'O', from:[6,0], to:[3,2]},
      {key:'P', from:[2,2], to:[3,6]},
      {key:'T', from:[3,5], to:[0,3]},
      {key:'K', from:[0,4], to:[2,6]},
    ],
    solution: [
      ['O','O','T','T','K','K','K','K','K'],
      ['O','O','T','T','T','K','K','K','K'],
      ['O','O','P','P','T','K','K','P','P'],
      ['O','O','O','P','T','T','P','P','P'],
      ['O','O','O','P','P','P','P','P','P'],
      ['O','O','O','P','P','G','G','R','R'],
      ['O','O','O','G','G','G','B','R','R'],
      ['Y','O','O','G','B','B','B','R','R'],
      ['Y','Y','Y','G','B','B','B','B','R'],
    ],
  },

  {
    id: 88, title: 'Great Maze', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,4], to:[7,6]},
      {key:'B', from:[7,7], to:[0,7]},
      {key:'G', from:[0,8], to:[6,8]},
      {key:'Y', from:[7,8], to:[8,0]},
      {key:'O', from:[7,0], to:[0,2]},
      {key:'P', from:[0,3], to:[1,1]},
      {key:'T', from:[2,1], to:[4,1]},
      {key:'K', from:[5,1], to:[2,2]},
    ],
    solution: [
      ['O','O','O','P','B','B','B','B','G'],
      ['O','P','P','P','B','B','B','B','G'],
      ['O','T','K','K','K','B','B','B','G'],
      ['O','T','K','K','K','B','G','G','G'],
      ['O','T','K','K','K','B','G','G','G'],
      ['O','K','K','K','K','B','B','B','G'],
      ['O','K','K','K','R','R','R','B','G'],
      ['O','K','K','K','R','R','R','B','Y'],
      ['Y','Y','Y','Y','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 89, title: 'Pipe Sage', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[0,6], to:[3,8]},
      {key:'B', from:[3,7], to:[1,2]},
      {key:'G', from:[1,3], to:[3,0]},
      {key:'Y', from:[3,1], to:[4,7]},
      {key:'O', from:[4,8], to:[5,7]},
      {key:'P', from:[5,6], to:[8,5]},
      {key:'T', from:[8,4], to:[7,5]},
      {key:'K', from:[6,5], to:[6,2]},
    ],
    solution: [
      ['G','G','B','B','B','B','R','R','R'],
      ['G','G','B','G','B','B','R','R','R'],
      ['G','G','G','G','B','B','R','R','R'],
      ['G','Y','Y','Y','Y','B','B','B','R'],
      ['K','K','K','K','Y','Y','Y','Y','O'],
      ['K','K','K','K','K','K','P','O','O'],
      ['K','K','K','T','T','K','P','P','P'],
      ['T','T','T','T','T','T','P','P','P'],
      ['T','T','T','T','T','P','P','P','P'],
    ],
  },

  {
    id: 90, title: 'Grandmaster', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[8,6], to:[4,7]},
      {key:'B', from:[5,7], to:[8,0]},
      {key:'G', from:[7,0], to:[2,5]},
      {key:'Y', from:[2,6], to:[1,5]},
      {key:'O', from:[0,5], to:[5,6]},
      {key:'P', from:[6,6], to:[6,4]},
      {key:'T', from:[5,4], to:[1,2]},
      {key:'K', from:[2,2], to:[5,5]},
    ],
    solution: [
      ['G','G','G','G','G','O','O','O','O'],
      ['G','T','T','G','G','Y','Y','Y','O'],
      ['G','T','K','G','G','G','Y','Y','O'],
      ['G','T','K','K','G','G','O','O','O'],
      ['G','T','T','K','K','K','O','R','R'],
      ['G','T','T','T','T','K','O','B','R'],
      ['G','T','T','T','P','P','P','B','R'],
      ['G','B','B','B','B','B','B','B','R'],
      ['B','B','B','B','B','B','R','R','R'],
    ],
  },

  {
    id: 91, title: 'Final Bend', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,6], to:[5,5]},
      {key:'B', from:[6,5], to:[5,4]},
      {key:'G', from:[5,3], to:[6,1]},
      {key:'Y', from:[6,2], to:[8,3]},
      {key:'O', from:[8,4], to:[7,6]},
      {key:'P', from:[7,7], to:[3,8]},
      {key:'T', from:[3,7], to:[4,2]},
      {key:'K', from:[3,2], to:[2,0]},
    ],
    solution: [
      ['K','K','K','K','T','T','T','T','T'],
      ['K','K','K','K','T','T','T','T','T'],
      ['K','K','K','K','K','T','T','T','T'],
      ['G','G','K','K','K','T','T','T','P'],
      ['G','G','T','T','T','T','R','R','P'],
      ['G','G','G','G','B','R','R','R','P'],
      ['G','G','Y','Y','B','B','R','R','P'],
      ['Y','Y','Y','Y','B','B','O','P','P'],
      ['Y','Y','Y','Y','O','O','O','P','P'],
    ],
  },

  {
    id: 92, title: 'Twin Coils', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,7], to:[0,8]},
      {key:'B', from:[1,8], to:[8,7]},
      {key:'G', from:[7,7], to:[8,5]},
      {key:'Y', from:[8,4], to:[2,3]},
      {key:'O', from:[2,4], to:[5,7]},
      {key:'P', from:[6,7], to:[6,4]},
      {key:'T', from:[5,4], to:[5,2]},
      {key:'K', from:[5,3], to:[7,3]},
    ],
    solution: [
      ['Y','Y','Y','R','R','R','R','R','R'],
      ['Y','Y','Y','R','R','R','R','R','B'],
      ['Y','Y','Y','Y','O','O','R','R','B'],
      ['Y','T','T','T','T','O','B','B','B'],
      ['Y','T','T','T','T','O','B','B','B'],
      ['Y','T','T','K','T','O','O','O','B'],
      ['Y','T','T','K','P','P','P','P','B'],
      ['Y','T','T','K','P','P','G','G','B'],
      ['Y','Y','Y','Y','Y','G','G','B','B'],
    ],
  },

  {
    id: 93, title: 'Vortex', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,8], to:[2,6]},
      {key:'B', from:[2,5], to:[1,2]},
      {key:'G', from:[1,1], to:[2,0]},
      {key:'Y', from:[2,1], to:[2,3]},
      {key:'O', from:[1,3], to:[2,4]},
      {key:'P', from:[3,4], to:[6,0]},
      {key:'T', from:[7,0], to:[8,5]},
      {key:'K', from:[8,6], to:[7,5]},
    ],
    solution: [
      ['G','G','B','B','B','B','B','R','R'],
      ['G','G','B','O','O','B','B','R','R'],
      ['G','Y','Y','Y','O','B','R','R','R'],
      ['P','P','P','P','P','R','R','R','R'],
      ['P','P','P','T','T','R','R','R','R'],
      ['P','P','P','T','T','R','R','R','R'],
      ['P','P','P','T','T','R','R','R','R'],
      ['T','P','P','T','T','K','K','K','K'],
      ['T','T','T','T','T','T','K','K','K'],
    ],
  },

  {
    id: 94, title: 'Riddle', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[7,7], to:[6,8]},
      {key:'B', from:[7,8], to:[8,6]},
      {key:'G', from:[8,5], to:[6,2]},
      {key:'Y', from:[7,2], to:[8,0]},
      {key:'O', from:[7,0], to:[4,1]},
      {key:'P', from:[3,1], to:[1,0]},
      {key:'T', from:[0,0], to:[2,7]},
      {key:'K', from:[2,8], to:[4,6]},
      {key:'N', from:[4,7], to:[5,1]},
    ],
    solution: [
      ['T','T','T','T','T','T','T','T','T'],
      ['P','T','T','T','T','T','T','T','T'],
      ['P','T','T','T','T','T','T','T','K'],
      ['P','P','N','N','N','K','K','K','K'],
      ['O','O','N','N','N','K','K','N','N'],
      ['O','N','N','N','N','N','N','N','N'],
      ['O','O','G','G','N','N','R','R','R'],
      ['O','O','Y','G','N','N','R','R','B'],
      ['Y','Y','Y','G','G','G','B','B','B'],
    ],
  },

  {
    id: 95, title: 'Crosshatch', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[3,3], to:[1,4]},
      {key:'B', from:[1,3], to:[2,6]},
      {key:'G', from:[3,6], to:[7,2]},
      {key:'Y', from:[7,1], to:[8,0]},
      {key:'O', from:[8,1], to:[8,4]},
      {key:'P', from:[7,4], to:[5,3]},
      {key:'T', from:[5,4], to:[6,6]},
      {key:'K', from:[6,7], to:[4,6]},
      {key:'N', from:[4,5], to:[5,7]},
    ],
    solution: [
      ['R','R','R','R','R','R','R','R','R'],
      ['R','R','R','B','R','R','R','R','R'],
      ['R','R','R','B','B','B','B','K','K'],
      ['R','R','R','R','G','G','G','K','K'],
      ['R','R','G','G','G','N','K','K','K'],
      ['Y','Y','G','P','T','N','N','N','K'],
      ['Y','Y','G','P','T','T','T','K','K'],
      ['Y','Y','G','P','P','T','T','K','K'],
      ['Y','O','O','O','O','T','T','K','K'],
    ],
  },

  {
    id: 96, title: 'Snarl Up', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[3,1], to:[0,0]},
      {key:'B', from:[1,0], to:[8,5]},
      {key:'G', from:[8,6], to:[6,4]},
      {key:'Y', from:[5,4], to:[3,2]},
      {key:'O', from:[3,3], to:[1,5]},
      {key:'P', from:[2,5], to:[2,7]},
      {key:'T', from:[2,8], to:[6,6]},
      {key:'K', from:[6,7], to:[7,8]},
      {key:'N', from:[6,8], to:[5,7]},
    ],
    solution: [
      ['R','R','O','O','O','O','P','P','P'],
      ['B','R','O','O','O','O','P','P','P'],
      ['B','R','O','O','O','P','P','P','T'],
      ['B','R','Y','O','O','T','T','T','T'],
      ['B','Y','Y','Y','Y','T','T','T','T'],
      ['B','Y','Y','Y','Y','T','T','N','N'],
      ['B','B','Y','Y','G','T','T','K','N'],
      ['B','B','Y','Y','G','G','G','K','K'],
      ['B','B','B','B','B','B','G','K','K'],
    ],
  },

  {
    id: 97, title: 'Maelstrom', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,0], to:[4,0]},
      {key:'B', from:[3,0], to:[0,0]},
      {key:'G', from:[0,1], to:[3,5]},
      {key:'Y', from:[4,5], to:[8,4]},
      {key:'O', from:[8,3], to:[8,1]},
      {key:'P', from:[8,0], to:[5,1]},
      {key:'T', from:[4,1], to:[5,4]},
      {key:'K', from:[6,4], to:[7,2]},
      {key:'N', from:[7,3], to:[7,7]},
    ],
    solution: [
      ['B','G','G','G','G','G','Y','Y','Y'],
      ['B','G','G','G','G','G','Y','Y','Y'],
      ['B','G','G','G','G','G','Y','Y','Y'],
      ['B','G','G','T','T','G','Y','Y','Y'],
      ['R','T','T','T','T','Y','Y','Y','Y'],
      ['R','P','T','T','T','Y','Y','Y','Y'],
      ['R','P','K','K','K','N','N','Y','Y'],
      ['P','P','K','N','N','N','N','N','Y'],
      ['P','O','O','O','Y','Y','Y','Y','Y'],
    ],
  },

  {
    id: 98, title: 'Endgame', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,2], to:[6,7]},
      {key:'B', from:[7,7], to:[0,7]},
      {key:'G', from:[0,6], to:[0,2]},
      {key:'Y', from:[1,2], to:[1,4]},
      {key:'O', from:[1,5], to:[2,7]},
      {key:'P', from:[3,7], to:[4,3]},
      {key:'T', from:[4,2], to:[5,0]},
      {key:'K', from:[6,0], to:[8,0]},
      {key:'N', from:[8,1], to:[7,3]},
    ],
    solution: [
      ['T','T','G','G','G','G','G','B','B'],
      ['T','T','Y','Y','Y','O','O','O','B'],
      ['T','T','P','P','P','O','O','O','B'],
      ['T','T','P','P','P','P','P','P','B'],
      ['T','T','T','P','P','P','P','P','B'],
      ['T','R','R','R','R','R','R','R','B'],
      ['K','R','R','N','N','R','R','R','B'],
      ['K','R','R','N','N','B','B','B','B'],
      ['K','N','N','N','N','B','B','B','B'],
    ],
  },

  {
    id: 99, title: 'The Summit', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[1,1], to:[2,2]},
      {key:'B', from:[1,2], to:[0,1]},
      {key:'G', from:[0,0], to:[5,3]},
      {key:'Y', from:[4,3], to:[5,4]},
      {key:'O', from:[5,5], to:[2,6]},
      {key:'P', from:[3,6], to:[5,7]},
      {key:'T', from:[4,7], to:[7,4]},
      {key:'K', from:[7,5], to:[6,6]},
      {key:'N', from:[6,5], to:[8,0]},
    ],
    solution: [
      ['G','B','B','B','O','O','O','O','O'],
      ['G','R','B','B','O','O','O','O','O'],
      ['G','R','R','Y','Y','O','O','O','O'],
      ['G','G','G','Y','Y','O','P','T','T'],
      ['G','G','G','Y','Y','O','P','T','T'],
      ['G','G','G','G','Y','O','P','P','T'],
      ['G','G','G','N','N','N','K','K','T'],
      ['G','G','G','N','T','K','K','K','T'],
      ['N','N','N','N','T','T','T','T','T'],
    ],
  },

  {
    id: 100, title: 'Dotwise', difficulty: 'expert', gridSize: 9,
    dots: [
      {key:'R', from:[6,0], to:[5,3]},
      {key:'B', from:[5,2], to:[2,0]},
      {key:'G', from:[2,1], to:[1,0]},
      {key:'Y', from:[0,0], to:[1,3]},
      {key:'O', from:[0,3], to:[0,6]},
      {key:'P', from:[1,6], to:[8,8]},
      {key:'T', from:[8,7], to:[6,6]},
      {key:'K', from:[7,6], to:[5,6]},
      {key:'N', from:[5,7], to:[4,4]},
    ],
    solution: [
      ['Y','Y','Y','O','O','O','O','P','P'],
      ['G','G','Y','Y','N','N','P','P','P'],
      ['B','G','B','B','N','N','N','P','P'],
      ['B','B','B','B','N','N','N','P','P'],
      ['R','R','B','B','N','N','N','N','P'],
      ['R','R','B','R','R','K','K','N','P'],
      ['R','R','R','R','R','K','T','T','P'],
      ['R','R','R','R','R','K','K','T','P'],
      ['R','R','R','R','R','K','K','T','P'],
    ],
  },
];
